### ISSUE TITLE
create_admin error code

### ISSUE THREAD

**Issue by mottosso** [cgwire/zou#1]
### Problem

Calling `zou create_admin` and handing it an invalid password returns error code 0, which makes it tricky to chain commands.

**Scenario 1**

```bash
$ zou create_admin && echo Success || echo Failure
Please enter an email for the new admin to create.
Email: my@email.com
Please enter a password for the new admin to create.
Password: pass
Password confirmation: pass
Passwords is too short.
Success
```

**Scenario 2**

```bash
$ zou create_admin && echo Success || echo Failure
Please enter an email for the new admin to create.
Email: my@email.com
Please enter a password for the new admin to create.
Password: password1
Password confirmation: password2
Passwords don't match.
Success
```

**Comment by frankrousseau** [comment]
Thank you @mottosso for reporting. I'm preparing a big update of Zou. I will do my best to include the fix into it.

**Comment by frankrousseau** [comment]
I think it should be fixed by recent changes. Could you give a try?

**Comment by mottosso** [comment]
Thanks, I'll give this a try soon.

**Comment by mottosso** [comment]
Works and looks good!

**Comment by frankrousseau** [comment]
Great! Thank you again @mottosso
