### ISSUE TITLE
Missing dependency in documentation

### ISSUE THREAD

**Issue by eliemichel** [cgwire/zou#107]
Just a quick fix, but I couldn't not find the source of the doc to make a PR:

The package `postgresql-server-dev-all` must be installed for psycopg, but it is not mentionned in the Dependencies section of [https://zou.cg-wire.com/](https://zou.cg-wire.com/).

(using Debian Jessie)

**Comment by frankrousseau** [comment]
Hello @eliemichel, thank you for the PR.

The documentation sources are in the `docs` branch: https://github.com/cgwire/zou/tree/docs

**Comment by frankrousseau** [comment]
Is that a Debian package or a Pypi package?

**Comment by eliemichel** [comment]
With the Pypi package. I followed https://zou.cg-wire.com/.

**Comment by frankrousseau** [comment]
Thx for the fix
