### ISSUE TITLE
Non ActiveDirectory LDAP not working

### ISSUE THREAD

**Issue by flablog** [cgwire/zou#130]
Hi !
We are using a LDAP directory in our infrastructure but it' s not Active Directory. So the implementation is different in some points. That said, the sync (and obviously the authentication) are not working out of the box. Some parameters are changing, some attributes do not exists.

Based on the current sync script, I tried to edit what has to change in order to work in our case (using a synology LDAP service). Differences are pointed in the comments

```
import ldap3
import os

LDAP_HOST = os.getenv("LDAP_HOST", "127.0.0.1")
LDAP_PORT = os.getenv("LDAP_PORT", "389")
LDAP_PASSWORD = os.getenv("LDAP_PASSWORD", "")
LDAP_BASE_DN = os.getenv("LDAP_BASE_DN", "cn=Users,dc=studio,dc=local")
LDAP_DOMAIN = os.getenv("LDAP_DOMAIN", "")
LDAP_USER = os.getenv("LDAP_USER", "")
EMAIL_DOMAIN = os.getenv("EMAIL_DN", "studio.local")
LDAP_EXCLUDED_ACCOUNTS = os.getenv("LDAP_EXCLUDED_ACCOUNTS", "")

# Main changes are in the user and server : 
# BEFORE : 
user = "%s\%s" % (LDAP_DOMAIN, LDAP_USER)
ldap_server = "%s:%s" % (LDAP_HOST, LDAP_PORT)
# AFTER : 
user = "uid=%s,%s" % (LDAP_USER, LDAP_BASE_DN) 
ldap_server = LDAP_HOST # No Domain

server = ldap3.Server(ldap_server, get_info=ldap3.ALL)
conn = ldap3.Connection(
    LDAP_HOST,
    user=user,
    password=LDAP_PASSWORD,
    # authentication=ldap3.NTLM, # NTLM -> Microsoft auth, not working here
    raise_exceptions=True,
    auto_bind=True)

attributes = [
           "givenName",
           "sn",
           #"sAMAccountName", -> Microsoft identifier, not available
           "mail",
           #"thumbnailPhoto" -> attribute not available neither 
       ]
conn.search(LDAP_BASE_DN, '(objectclass=person)', attributes=attributes)

for entry in conn.entries:
    print(entry)

```

As for attributes, some works, some don't has specified in the comments. But even though they work, we are not using them. So how can we specify which attributes to use ? Example, `sAMAccountName` might be replaced by attribute `cn` or `uid`. We have nothing to use as `thumbnailPhoto`, the first and last name are stored in another place (which I won't trust to be right and looks more a Synology wrong usage of the field). We also might use the `ShadowExpire` to know if a user can or can not log in (user disabled set the value of that attribute to `-1`)
Which other information do you need ? 
Cheers !

**Comment by frankrousseau** [comment]
Thank you @flablog for reporting. We'll see what we can do for that.

**Comment by frankrousseau** [comment]
With the last update, it should work. Let me know when you can try it again!

**Comment by BigRoy** [comment]
@flablog to follow up on this, are you able to confirm this has been fixed?

**Comment by frankrousseau** [comment]
ping @flablog
