### ISSUE TITLE
Task estimation time can not be a float

### ISSUE THREAD

**Issue by flablog** [cgwire/zou#133]
Apparently, when setting the estimation time of a task, we can only set an int. Any other try, with a `dot` or `comma` makes the action runs forever without feedback. Meanwhile in the server, an error message is raised. It's obvious here that an int is required.

```
[SQL: 'UPDATE task SET updated_at=%(updated_at)s, estimation=%(estimation)s WHERE task.id = %(task_id)s'] [parameters: {'updated_at': datetime.datetime(2019, 2, 20, 10, 28, 14, 586337), 'estimation': '', 'task_id': UUID('5daa066c-c727-435a-a84c-b344f85617f4')}] (Background on this error at: http://sqlalche.me/e/9h9h)
[2019-02-20 10:28:30,167] ERROR in base: (psycopg2.DataError) invalid input syntax for integer: "3.4"
LINE 1: ...019-02-20T10:28:30.152769'::timestamp, estimation='3.4' WHER..
```

So how to set a 2 hours estimated task ?
And the gui should return an error maybe ? Or allow only for ints inputs.

**Comment by frankrousseau** [comment]
Thank you @flablog for reporting. That's definitely a bug.

**Comment by frankrousseau** [comment]
After a second thought. I think it's better to keep it as an int. It will more consistent with the duration field.  I will change Kitsu, so it stores the estimation in minutes before saving it to database. Are you ok with that idea?

**Comment by flablog** [comment]
I guess I'm good with it
As long as we can define something else than just days, even if it's in
minutes :)

Le lun. 25 févr. 2019 à 13:45, Frank Rousseau <notifications@github.com> a
écrit :

**Comment by frankrousseau** [comment]
We fixed this. We decide to change things in the UI and considered estimations as minutes.
