### ISSUE TITLE
Query login tokens through browser session

### ISSUE THREAD

**Issue by BigRoy** [cgwire/zou#152]
### Idea

Would it be possible to query the currently logged in user through a browser session so that, to login with `gazu` one does not need to enter credentials if they are currently logged in online.

I've seen some code for this with other production trackers/managers and was wondering whether that could be a possibility here too?

Reference implementation:
- [Ftrack](https://bitbucket.org/ftrack/ftrack-connect/src/5d1a4c4843f6c414009f65ed40be941b977f1bd4/source/ftrack_connect/ui/application.py#lines-231)

**Comment by frankrousseau** [comment]
We are not comfortable with this. Shared sessions between browsers and desktop application, doesn't seem secure.  We'll investigate this idea but we don't want to promise anything about it.

**Comment by BigRoy** [comment]
Actually no I haven't. Haven't looked into it anymore.

**Comment by mathbou** [comment]
Hey guys, I recently encountered the same problem, and I found a way to manage this. It's kind of dark magic but it works well.
The process relies on the fact that Kitsu stores the access token as a browser cookie. Knowing that we can use the module [browser-cookie3](https://pypi.org/project/browser-cookie3) to get it from chrome or firefox. For python2 there is a fork of [browsercookie](https://github.com/Jaminb2030/browsercookie) that works, but it does not have the domain filtering feature.

Here is an example:

```python
import traceback
import browser_cookie3 as browsercookie

from getpass import getuser

import gazu
from gazu.exception import NotAuthenticatedException, AuthFailedException


cookies = browsercookie.load("kitsu.url")
cookie_names = ["access_token_cookie",
                "refresh_token_cookie"]

tokens = dict()
for cookie in cookies:
    if cookie.name in cookie_names:
        token_name = cookie.name.replace("_cookie", "")
        tokens[token_name] = cookie.value


gazu.set_host("http://kitsu.url/api")
gazu.client.set_tokens(tokens)

try:
    user = gazu.client.get_current_user()
except (AuthFailedException, NotAuthenticatedException):
    traceback.print_exc()
else:
    # If you're using a LDAP or an AD you can check that the cookie owner is also the current user
    if user.get("desktop_login") == getuser():
        print("Connected")
    else:
        print("Mismatching usernames")
        gazu.client.set_tokens({})  # Force disconnection

```

**Comment by frankrousseau** [comment]
Awesome! could you add this somewhere in the Gazu documentation?
