### ISSUE TITLE
werkzeug version 

### ISSUE THREAD

**Issue by cameronpd** [cgwire/zou#169]
Hi,

Just upgraded to zou 0.10.20 to test API event changes and saw this in the pip output:

```
flask 1.1.1 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.14.1 which is incompatible.
```
  
Cameron

**Comment by frankrousseau** [comment]
Hello,

Can you try to run `pip install --upgrade werkzeug` in you zou virtual environment?

**Comment by cameronpd** [comment]
I actually tried that right away and it worked fine as far as I could tell. Just wanted to report it so that it's known about.

**Comment by frankrousseau** [comment]
It should be fixed in next version. I forced the right version in the dependency list.
