### ISSUE TITLE
Installation Zou

### ISSUE THREAD

**Issue by F-Brar** [cgwire/zou#187]
Hi there,

I am trying to setup the zou API on my raspberry4 for testing purposes. I followed the documentation for installation. When i try executing the following command:
`DB_PASSWORD=yourdbpassword zou init_db`
i get the following message:
`Cannot access to the required Redis instance`

In the doc it says: "Currently Redis require no extra configuration."
I am new to redis and server-related stuff in general so i guess there is a step i am missing that might be very obvious.

Thanks for supplying these tools!

**Comment by frankrousseau** [comment]
Hello @F-Brar,

Can you give us more context about your situation: for which studio and for which kind of production do you want to use Kitsu?

About your problem: did you install Redis properly? On which distribution did you run the installation?

**Comment by frankrousseau** [comment]
The error message is weird. It says that everything is fine and by the same time it says that something went wrong the PID file. I think you should first solve the PID file issue to make sure that everything is ok.

**Comment by frankrousseau** [comment]
What is your distribution?

**Comment by F-Brar** [comment]
I am using Raspbian Buster Lite. I should probably also mention that I am running a nextcloud on Apache2 next to redis and nginx. Maybe a fresh install would be better?

**Comment by frankrousseau** [comment]
Not sure. Of course, limited resources can be a problem. But for a few queries like login, it should be enough. It seems there is an issue with the Redis install too.
