### ISSUE TITLE
LDAP sync failing on previously created accounts

### ISSUE THREAD

**Issue by flablog** [cgwire/zou#208]
If I have created an account, for example the first admin account, with an email also present in the LDAP, there is an error while synchronizing the LDAP with the _zou sync_with_ldap_server_ utility.

> sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "person_email_key"
> DETAIL:  Key (email)=(xxx@xxx.com) already exists

Only the desktop login appears to be tested https://github.com/cgwire/zou/blob/master/zou/app/utils/commands.py#L240-L244

**Comment by frankrousseau** [comment]
It should be fixed. Can you verify?
