### ISSUE TITLE
LDAP Environment variable LDAP_IS_AD not working properly

### ISSUE THREAD

**Issue by flablog** [cgwire/zou#209]
On the zou.service file, while connecting to an LDAP server you can use the LDAP_IS_AD variable. But it does not appears to create a boolean while initializing the zou instance, so it does not work as expected later on.

It's true at least using :
Environment="LDAP_IS_AD=False"
The LDAP connection is returning :
> raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
> ldap3.core.exceptions.LDAPAuthMethodNotSupportedResult: LDAPAuthMethodNotSupportedResult - 7 - authMethodNotSupported - None - unknown authentication method - bindResponse - None

So far, leaving that variable unset (which is defined to False by Default) works in my case

**Comment by frankrousseau** [comment]
It should be fixed. Can you verify?
