### ISSUE TITLE
create_admin does not create valid account

### ISSUE THREAD

**Issue by pcdinh** [cgwire/zou#214]
Hi,

I followed installation guide at https://zou.cg-wire.com/#install to install Zou 0.11 in my local computer and found that the command

```
DB_PASSWORD=yourdbpassword zou create_admin adminemail@yourstudio.com
```

does not allow me to create a valid admin account

```
(zouenv) ubuntu@mts2:/opt/zou$ DB_PASSWORD=xxxxx zou create_admin ubuntu@gmail.com
Admin successfully created.
```

It does not ask me to specify a password. So I logged in using "default" as password as the docs says

```
Then your user will be created with the email as login, default as password and "Super Admin" as first name and last name.
```

However, login with such credentials does not work. 

It says

```
Log in failed, please verify your credentials 
```

Basically I understand that admin account must be activated first. However, the installation guide says nothing about email server configuration. Also, when the admin account is created without verification and email server not properly setup, there is no feature to fix it.

Is it a bug or am I missing something?

Regards,

Dinh

**Comment by pcdinh** [comment]
I logged in zoudb database and found that

```
zoudb=# select active, email from person;
 active |       email
--------+--------------------
 t      | ubuntu@gmail.com
```

`active` is set to `true`. So `ubuntu@gmail.com` is activated by default. The message `Log in failed, please verify your credentials` is very confused

**Comment by ddesmond** [comment]
This sound like your postegress hb config is "not set properly". Can you try to change config in hba config like written here:
[https://www.linode.com/docs/databases/postgresql/how-to-install-postgresql-relational-databases-on-centos-7/#secure-postgresql](https://www.linode.com/docs/databases/postgresql/how-to-install-postgresql-relational-databases-on-centos-7/#secure-postgresql)
try changing it to md5 or trust and see if that works for you! :)

**Comment by pcdinh** [comment]
Thanks for your support. I checked Chrome debugger and found that the server response was 

```
{"error": true, "login": false, "message": "Database doesn't seem reachable."}
```

The  I checked Zou log at `/opt/zou/logs` and found that PostgreSQL did not allow local authentication via password. I changed `pg_hba.conf` to enable it.

However, Kitsu, the Zou front-end does not understand it. Its response

```
Log in failed, please verify your credentials
```

is very misleading

**Comment by frankrousseau** [comment]
You're right.
But for your information after a new install, you have to check the status endpoint: 

```
curl http://localhost:5000/status
```

**Comment by frankrousseau** [comment]
Can I close this issue?
