### ISSUE TITLE
The notification emails are not showing correctly in email client

### ISSUE THREAD

**Issue by ddesmond** [cgwire/zou#216]
The Production tracker emails (as html formatting in email client) shows correctly.
The notification emails are not showing correctly (as html formatting in email client).

The expected behavior is:
Show correctly HTML tags for email notifications.

**Comment by frankrousseau** [comment]
Thank you @ddesmond for reporting

**Comment by ddesmond** [comment]
<img width="944" alt="Screenshot 2019-12-28 at 17 18 28" src="https://user-images.githubusercontent.com/2397041/71546347-3b99f480-2996-11ea-9011-81dc11c26306.png">
@frankrousseau

**Comment by frankrousseau** [comment]
Thx, it should be fixed in next release.

**Comment by frankrousseau** [comment]
Does it work better after update?

**Comment by ddesmond** [comment]
Will update and send you feedback after testing.

**Comment by ddesmond** [comment]
ive updated all to latest, html is working just fine! Will close the issue as resolved.
Thanks Frank and kitsu team :)
