### ISSUE TITLE
Events handlers doesn't work

### ISSUE THREAD

**Issue by Tilix4** [cgwire/zou#219]
I've followed this doc: https://zou.cg-wire.com/events/

I've created my own directory for events handlers in `zou.service`:

`Environment="EVENT_HANDLERS_FOLDER=/home/user/apps/zou/handlers" `

I've given the ownership to zou for this folder.
I've restarted zou service.

I've created the __init__py:

```
import test
 
event_map = {
    "asset:new": test,
}
```

I've created a test.py:

```
def handle_event(data):
    with open("Output.txt", "w") as text_file:
        print(data, file=text_file)
```

I create a new asset, but it doesn't create my file.   

_Also, I know where to look at this `print()`, as the documentation uses it._

**Comment by jasperges** [comment]
Going through the code of Zou, you can find [the function responsible for registering event handlers](https://github.com/cgwire/zou/blob/master/zou/app/api.py#L64):

```python
def register_event_handlers(app):
    """
    Load code from event handlers folder. Then it registers in the event manager
    each event handler listed in the __init_.py.
    """
    sys.path.insert(0, app.config["EVENT_HANDLERS_FOLDER"])
    try:
        import event_handlers

        events.register_all(event_handlers.event_map, app)
    except ImportError:
        # Event handlers folder is not properly configured.
        # Handlers are optional, that's why this error is ignored.
        app.logger.info("No event handlers folder is configured.")
    return app
```

As you can see it tries to import `event_handlers` after inserting your event handlers folder in the Python path. So in your event handlers folder you should create another folder (package) with the name `event_handlers` containing the `__init__,py` and your handlers.

I found that quite confusing and – like you – didn't understand why it was not working at first. This should be better documented or (even better) changed so that it reads directly from the event handlers folder in my opinion.

**Comment by Tilix4** [comment]
Thanks for answering.

I've created an event_handlers folder. Moved my scripts in it, but it still doesn't work. It doesn't create the file.

**Comment by frankrousseau** [comment]
I improved the documentation. Does it make things clearer? https://zou.cg-wire.com/events/

**Comment by Tilix4** [comment]
It's more explicit but I still don't know where I can check the `current_app.logger.info("Event occured!")` output.
Also, with:
```
def handle_event(data):
    with open("Output.txt", "w") as text_file:
        print(data, file=text_file)
```
I still don't have any output file next to my _test.py_, even though I did eveything mentionned in the doc.

**Comment by frankrousseau** [comment]
You should be able to find the output in `/opt/zou/logs/guincorn_access.log`. If it doesn't work you can try to log an error (current_app.logger.error("...") and look at /opt/zou/logs/guincorn_error.log`

**Comment by Tilix4** [comment]
I'm sorry Frank but I cannot display anything like this...

**Comment by jasperges** [comment]
@frankrousseau Thanks for updating the documentation!

**Comment by Tilix4** [comment]
Okay, it finally works.  
I found out that I didn't configure the jobs correctly and then it was causing trouble. (For now I disabled them) 
Also, by default it was writing my _Output.txt_ file in `/opt/zou`.

After all, I had the error message in `/opt/zou/logs/gunicorn_error.log` printed by `current_app.logger.info("Event occured!")
`

**Comment by frankrousseau** [comment]
Great because I had no idea of why it didn't work
