### ISSUE TITLE
timeout de l'event stream

### ISSUE THREAD

**Issue by sayanel** [cgwire/zou#22]
- rappel: rajouter events à la fin de proxy_pass pour la section location /events dans conf.d/zou.conf:
`proxy_pass: http://localhost:5001/events` 
(il y avait une erreur dans la doc la dernière fois)

- concernant zou-events, tout fonctionne parfaitement, l'actualisation automatique se fait bien quand on a deux pages ouvertes mais au bout de quelques minutes on retrouve le message suivant:

> Firefox ne peut établir de connexion avec le serveur à l’adresse http://<ip>/events.

**Comment by frankrousseau** [comment]
Merci pour ce rapport de bug. Je m'attaque à ça la semaine prochaine.

**Comment by frankrousseau** [comment]
Le problème s'avère plus compliqué que prévu. Je vais probablement devoir mettre en place un système de websockets. Je n'ai pas encore déterminé quand je mettrai ça en place.

**Comment by frankrousseau** [comment]
Je pense revoir complètement ce mécanisme pour le remplacer par des websockets. L'event stream tel qu'il est codé fonctionne trop mal.

**Comment by frankrousseau** [comment]
L'event stream a été remplacé par un système de websockets. Je clos l'issue.
