### ISSUE TITLE
Error deleting user

### ISSUE THREAD

**Issue by 0anion0** [cgwire/zou#222]
I need to delete the user. When deleting, an error occurs: "An error occured while deleting this person. There are probably data linked to it. Are you sure this person has no assignation or wrote no comment?"

ERROR:  update or delete on table "person" violates foreign key constraint "api_event_user_id_fkey" on table "api_event"
DETAIL:  Key (id)=(0e4bd876-8d7f-438b-abb7-368344aaecf3) is still referenced from table "api_event".
STATEMENT:  DELETE FROM person WHERE person.id = '0e4bd876-8d7f-438b-abb7-368344aaecf3'::uuid

The problem appears after deleting the project in which there was a task for the user.

**Comment by frankrousseau** [comment]
Thank you for reporting @0anion0.

**Comment by frankrousseau** [comment]
It should be fixed in next release.
