### ISSUE TITLE
relations parameter in get request

### ISSUE THREAD

**Issue by pcharmoille** [cgwire/zou#232]
Hello,

Zou allow to retrieve entities with or without serialized related entities (attributes declared as sqlalchemy `relationship`.
For example `outputs` in `WorkingFile` model.

Sometime we need to query entities with their relatations but there is no way to specify it.
Could we consider add a `with_relation` paramater to `get` requests to retrieve entites with or without their relations ?
Default value would be `False` to stay as fast as possible.

**Comment by frankrousseau** [comment]
Hello,

You can already do it with the `relations=true` flag (not sure it's documented):
https://github.com/cgwire/zou/blob/master/zou/app/blueprints/crud/base.py#L141

**Comment by pcharmoille** [comment]
Cool ! But it does only works with base model right ?
If we wanted to get all the assets of a projet with their relations, we would have to use the `ProjectAssetsResource` and then query again the asset one by one with `relations` flag to True.

Could we consider something like this 
```python
class ProjectAssetsResource(Resource):
    @jwt_required
    def get(self, project_id, relations=False):
        """
        Retrieve all assets for given project.
        """
        user_service.check_project_access(project_id)
        criterions = query.get_query_criterions_from_request(request)
        criterions["project_id"] = project_id
        return assets_service.get_assets(
            criterions, relations=relations)
```

It would be tedious to add for every custom get method but I could be done progressively.
Or we can keep the current 2 requests way for clarity.

**Comment by frankrousseau** [comment]
Yes it should be something like this. But I think that you cannot give query parameter this way. You have to rely on the `request.args` dict to retrieve the `relations` flag.

**Comment by pcharmoille** [comment]
Ok, I am going to make a PR related to this issue then.

**Comment by pcharmoille** [comment]
So this is what it would looks like :
Zou
```python
class TaskWorkingFilesResource(Resource):
    """
    Return all working file revisions for a given task.
    """

    @jwt_required
    def get(self, task_id):
        result = {}

        task = tasks_service.get_task(task_id)
        user_service.check_project_access(task["project_id"])

        options = request.args
        relations = options.get("relations", "false").lower() == "true"

        result = files_service.get_working_files_for_task(
            task["id"],
            relations=relations)

        return result
```

Gazu
```python
@cache
def get_working_files_for_task(task, full=False):
    """
    Args:
        task (str / dict): The task dict or the task ID.
        full (bool): Should all relations be added to task description

    Returns:
        list: Working files related to given task.
    """
    task = normalize_model_parameter(task)
    path = "data/tasks/%s/working-files" % task["id"]
    params = {'relations': full}
    return client.get(path, params)
```

I am not 100% sure that this is the most efficient way to do it since it will ask us to add parameters in most of gazu and zou services methods.
There could be another way using a session attribute defined by the gazu client and use it in the `serialize_models` method as a default value. 

Let me know what you think.

**Comment by frankrousseau** [comment]
Too old issue. Let's close it.
