### ISSUE TITLE
Error while installing zou

### ISSUE THREAD

**Issue by artofka** [cgwire/zou#249]
Here is python log:
[logZouInstall.txt](https://github.com/cgwire/zou/files/4601044/logZouInstall.txt)

**Comment by frankrousseau** [comment]
Hello,

Thank you for your interest in Kitsu. What OS do you use for the installation?

**Comment by artofka** [comment]
Thanks for response! Ubuntu 20.04 LTS

**Comment by frankrousseau** [comment]
Ok sorry, but we don't do support for 20.04. We recommend you to install it on Ubuntu 18.04.

NB: The problem may be related to PIL library version. We'll upgrade it, it may fix your problem.

**Comment by artofka** [comment]
For 18.04 all is fine. Thanks for response!
