### ISSUE TITLE
Error after Deploying Kitsu

### ISSUE THREAD

**Issue by artofka** [cgwire/zou#250]
Error: 
![image](https://user-images.githubusercontent.com/28753260/81501078-f344f880-92de-11ea-9ade-51df0eede502.png)

**Comment by frankrousseau** [comment]
It's because the server is not started. Can you tell us what there is in the log file `/opt/zou/logs/gunicorn_error.log`?

**Comment by artofka** [comment]
Folder for logs is empty

**Comment by artofka** [comment]
Also I getting 502 bad gateway while trying https://localhost/api

**Comment by frankrousseau** [comment]
What does it say when you run `sudo service zou start`?

**Comment by artofka** [comment]
Nothing

**Comment by frankrousseau** [comment]
And `ps -ef | grep zou`?

**Comment by artofka** [comment]
artem    150  1979  0 19:50 pts/0    00:00:00 grep --color=auto zou

**Comment by artofka** [comment]
Problem is still actual

**Comment by artofka** [comment]
re-installing from scratch was successful. Not having that issue now.

**Comment by frankrousseau** [comment]
Ok great! I didn't have any idea of what was going wrong.
