### ISSUE TITLE
AttributeError: 'Person' object has no attribute 'present_mimimal'

### ISSUE THREAD

**Issue by OxB03** [cgwire/zou#265]
"/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/blueprints/crud/person.py"

line 67: should be 
             return instance.present_minimal()
not
             return instance.present_mimimal()

Apologies, don't know how to do pull requests yet, but thought this might help ...

**Comment by frankrousseau** [comment]
Many thanks, that's useful!

**Comment by frankrousseau** [comment]
It will be fixed in next release

**Comment by OxB03** [comment]
Resolved
