### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by fsiddi** [cgwire/zou#272]
When getting zou up and running for the first time with the command (as mentioned in the docs)

```
FLASK_DEBUG=1 FLASK_APP=zou.app flask run
```
 I get a `ValueError: signal only works in main thread` error when visiting `localhost:5000`. 

A quick search mentions an [issue with Flask-SocketIO](https://stackoverflow.com/questions/53522052/flask-app-valueerror-signal-only-works-in-main-thread), but I'm not sure this is the cause or if the issue is due to some misconfiguration on my end. Any advice?

**Comment by frankrousseau** [comment]
Hello @fsiddi,
The command you are using must be used only for development purposes. And as you noticed, there is an issue with flask-socketio. You can use `--no-reload` to avoid this error. I'm going to add a debug runner as suggested in the issue you mention.

**Comment by frankrousseau** [comment]
I added a command for this

```
DEBUG=1 MAIL_DEBUG=1 FLASK_DEBUG=1 FLASK_APP=zou.app python zou/debug.py
```
