### ISSUE TITLE
PREVIEW_FOLDER default value

### ISSUE THREAD

**Issue by fsiddi** [cgwire/zou#273]
In [the documentation](https://zou.cg-wire.com/configuration/), the value of `PREVIEW_FOLDER` is mentioned to be `/usr/local/share/zou/standard`, but looking at `config.py` I find this:

```
PREVIEW_FOLDER = os.getenv("PREVIEW_FOLDER", os.getenv("THUMBNAIL_FOLDER", "previews"))
```

on macOS this leads to thumbnails not being saved:

```
127.0.0.1 - - [30/Aug/2020 18:52:23] "POST /pictures/thumbnails/persons/c2f40d61-e83c-4f6c-b24f-67c9b19e33b5 HTTP/1.1" 201 -
[2020-08-30 18:52:23,722] ERROR in resources: [Errno 2] No such file or directory: '/Users/fsiddi/Developer/zou/zou/app/previews/pictures/thumbnails/c2f/40d/c2f40d61-e83c-4f6c-b24f-67c9b19e33b5'
127.0.0.1 - - [30/Aug/2020 18:52:23] "GET /pictures/thumbnails/persons/c2f40d61-e83c-4f6c-b24f-67c9b19e33b5.png?unique=zdhb5 HTTP/1.1" 404 -
```

After manually setting `PREVIEW_FOLDER` to an absolute path I was able to save previews correctly. I think it might be a good idea to clarify the default value, but I'm not sure about the expectations for the default behavior.

**Comment by frankrousseau** [comment]
Thank you @fsiddi. You're right the documentation is wrong. We are going to fix this. The default value is made for development environments, the preview folder is a `previews` subdirectory of your working environment.

**Comment by frankrousseau** [comment]
Fixed
