### ISSUE TITLE
Mismatching values between shots/assets and entities path

### ISSUE THREAD

**Issue by mathbou** [cgwire/zou#275]
__Issue:__

When querying shots or assets with the REST api I get key with mismatching values. In the following example I queried a shot with the _shots_ and _entities_ path and I get a mismatch on the _type_ key and the _source_id_ key. 
Also, I'm wondering if is it normal that the _source_id_ default value is the string "None" instead of a __null__ ?

__Examples:__

/api/data/shots
```json
{
	"canceled": false,
	"data": {},
	"description": null,
	"entity_type_id": "fc757eb4-8f3f-4fce-adce-3b665c28d737",
	"episode_id": "e3ae3a2d-63ac-4a65-8bce-5453759f398a",
	"episode_name": "E01",
	"fps": null,
	"frame_in": null,
	"frame_out": null,
	"id": "0147e85e-df1a-409b-a495-f98cf0c8abe7",
	"name": "sh02",
	"nb_frames": null,
	"parent_id": "66a18ac0-d710-473c-83ca-a3010f3a14e9",
	"preview_file_id": "",
	"project_id": "66b51720-1e5c-4599-8c98-f8f3c901b7fb",
	"project_name": "truc ",
	"sequence_id": "66a18ac0-d710-473c-83ca-a3010f3a14e9",
	"sequence_name": "sq01",
	"source_id": "None",
	"tasks": [],
	"type": "Shot"
}
```

/api/data/entities
```json
{
	"entities_out": [],
	"instance_casting": [],
	"created_at": "2020-09-02T13:11:45",
	"updated_at": "2020-09-02T13:11:45",
	"id": "0147e85e-df1a-409b-a495-f98cf0c8abe7",
	"name": "sh02",
	"code": null,
	"description": null,
	"shotgun_id": null,
	"canceled": false,
	"nb_frames": null,
	"project_id": "66b51720-1e5c-4599-8c98-f8f3c901b7fb",
	"entity_type_id": "fc757eb4-8f3f-4fce-adce-3b665c28d737",
	"parent_id": "66a18ac0-d710-473c-83ca-a3010f3a14e9",
	"source_id": null,
	"preview_file_id": null,
	"data": null,
	"entities_in": [],
	"type": "Entity"
}
```

Cg-Wire version: Kitsu 0.12.0 // Zou 0.12.0

**Comment by frankrousseau** [comment]
Sorry, I don't understand what is wrong. Can you be more explicit?

**Comment by mathbou** [comment]
When I query a shot, shouldn't I get `"type": "Shot"` for both queries? (from data/entities and data/shots). And same for the _source_id_, shouldn't it be `"source_id": null` for both cases?

**Comment by frankrousseau** [comment]
Ok for the `source_id` field. For the entity list, it's a bit more complicated to fix that. It it something important for you?

**Comment by mathbou** [comment]
I have a workaround for now, but it implies to query the db 2 times instead of one.

**Comment by frankrousseau** [comment]
It should be fixed in latest version. Can you try it?
