### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by flinfo** [cgwire/zou#277]
Hey there. This is not so much an issue as a lack of my understanding.

> Finally, create database tables (it is required to leave the posgres console and to activate the Zou virtual environment):
> 
>  #Run it in your bash console.
> DB_PASSWORD=yourdbpassword zou init_db

So as instructed, I leave postgres and exit virtualenv and am back as my user and are told to run this DB_PASSWORD command.
And my beginner understanding says this doesn't look like a command and when I enter it I get the expected:

> chirp@chirp:/opt/zou$ DB_PASSWORD=mysecretpassword zou init_db
> Command 'zou' not found, did you mean:
>   command 'zmu' from deb zoneminder (1.32.3-2build1)

Sorry, I know this is probably really dumb, but could you please instruct me on what to do here?

Thanks

**Comment by frankrousseau** [comment]
A virtual environment is a copy of the Python executable. It has his own set of libraries which overrides the common set of Python libraries of your system when it is up. If you install libraries and binaries while being in the virtual environment (like zou) and then leave it. You cannot access to them anymore. 
In other words, if you want to run zou commands, the virtualenv must be activated.
