### ISSUE TITLE
Errors appear when upgrading ZOU

### ISSUE THREAD

**Issue by 0anion0** [cgwire/zou#282]
Hello, I need help.
Errors appear when upgrading ZOU

```
UPGRADE ZOU
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

Tell me how to solve this problem.

**Comment by frankrousseau** [comment]
Hello @0anion0. There are only warnings. It doesn't seem that the command fails.

**Comment by mathbou** [comment]
@frankrousseau I made some research about those warnings and according to this [StackOverflow topic](https://stackoverflow.com/a/64038112), and the attached [issue](https://github.com/gevent/gevent/issues/1260), they seem to come from an incompatibility between gevent and gunicorn versions.

With the current setup.py, my docker images are stuck starting workers again and again, but I made a try with the version given in the topic (gunicorn==19.9.0 gevent==1.3.4 greenlet==0.4.13) and it starts normally. However, I can't tell for the whole zou feature set.

Now, why it's not working whereas the previous versions were, and with the same requirements? That's a mystery.

**Comment by mathbou** [comment]
An Interresting thing, I tried to force the pip --non-binary flag  for gevent, gunicorn and greenlet during the build of my zou image and it works again

**Comment by frankrousseau** [comment]
I upgrade Gunicorn and Gevent library versions. Does it fix the probleme?

**Comment by mathbou** [comment]
It looks like it does yes, thanks
