### ISSUE TITLE
s3 backend us-east-1 boto3 workaround

### ISSUE THREAD

**Issue by ninglesby** [cgwire/zou#294]
Hey I just started playing around with zou, and it is great! I found a little bug that is pretty easy to fix. I have never done a PR before, is this something I should do or is it small enough that it would be easier for someone else to take care of?

I was getting a LocationConstraint Error when trying to use s3. I found this [Boto3 Issue](https://github.com/boto/boto3/issues/125) , which seems to indicate that "us-east-1" is a special case and should not be used with LocationConstraint.

[file_store.py](https://github.com/cgwire/zou/blob/master/zou/app/stores/file_store.py)

``` python
    try:
        self.bucket.create(
            CreateBucketConfiguration={
                'LocationConstraint': config.region
            }
        )
    except self.s3.meta.client.exceptions.BucketAlreadyOwnedByYou:
        pass
```

I changed it to 

``` python
    try:
        if config.region == "us-east-1":
            self.bucket.create()
        else:
            self.bucket.create(
                CreateBucketConfiguration={
                    'LocationConstraint': config.region
                }
            )
    except self.s3.meta.client.exceptions.BucketAlreadyOwnedByYou:
        pass
```

And that seemed to do the trick.

**Comment by frankrousseau** [comment]
Hello @ninglesby,

Thank you for the information. And yes the best is that you make a PR to fix this problem.

**Comment by frankrousseau** [comment]
I made the fix. Can you confirm that it works?

**Comment by ninglesby** [comment]
It works, Thanks!
