### ISSUE TITLE
Slack Notification is not working

### ISSUE THREAD

**Issue by Shayen** [cgwire/zou#301]
Hi,
It seems like Slack Notification is not working even I set **SLACK NOTIFICATION ENABLED** to _**Yes**_ and Slack Username is also collected.

Zou 0.12.30

**Comment by frankrousseau** [comment]
Hello Shayen did you register your app properly in the admin part?

https://kitsu.cg-wire.com/slack/

**Comment by Shayen** [comment]
Yes, I have done every step in the guide. 
Is it because I'm using the docker version?

it looks like Python3 is used in the docker file but [chats.py](https://github.com/cgwire/zou/blob/master/zou/app/utils/chats.py) still call the slack module from Python 2 version.

**Comment by frankrousseau** [comment]
Yes, the Python 3 version requires a late version of Python 3 which would break many installations.

**Comment by frankrousseau** [comment]
Sometimes it comes from the fact that you don't have chosen the right user name. It's the nick handle, not the displayed user name that must be used.

**Comment by Shayen** [comment]
I'm totally sure that I use the collect display name, since the notification function is working properly when I ran it separately.

btw, What is the Python version is officially commended for Zou?

**Comment by frankrousseau** [comment]
Python 3 or superior. I think the v3 of Slack requires 3.6 or 3.8. But Ubuntu 18.04 comes with 3.5 by default.

**Comment by frankrousseau** [comment]
In fact you should not use the display name but the member ID provided in the Slack profile.
