### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by fananimi** [cgwire/zou#324]
Hi, I just install through the following command: 

`python3 setup.py install` 

An error is occurred due to dependencies version conflict.

```
...
warning: no files found matching '*.html'
warning: no files found matching '*.js'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
creating /usr/lib/python3.8/site-packages/socketIO_client-0.7.2-py3.8.egg
Extracting socketIO_client-0.7.2-py3.8.egg to /usr/lib/python3.8/site-packages
Adding socketIO-client 0.7.2 to easy-install.pth file

Installed /usr/lib/python3.8/site-packages/socketIO_client-0.7.2-py3.8.egg
error: requests 2.25.1 is installed but requests==2.24.0 is required by {'gazu'}
The command '/bin/sh -c python3 setup.py install' returned a non-zero code: 1
```

**Comment by frankrousseau** [comment]
Ok. Thank you for notifying us! We will fix that for the next release. Because you're in development mode, you can bypass this by modifying the request version is the `setup.cfg` file.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by fananimi** [comment]
Thanks @frankrousseau , I will test soon.

**Comment by fananimi** [comment]
Hi @frankrousseau,

I have a similar issue right now. Please find bellow:

![Selection_053](https://user-images.githubusercontent.com/497424/110687069-b2758300-8212-11eb-8127-13f0a060f3a5.png)

And here how I solve it:

![Selection_054](https://user-images.githubusercontent.com/497424/110687143-c7521680-8212-11eb-96e7-7f96530bf923.png)

Thanks.
