### ISSUE TITLE
Concurrent annotation edit conflict

### ISSUE THREAD

**Issue by dee909** [cgwire/zou#325]
If two users are adding or removing playlist annotations on the same asset/shot at the same time, on of them will lose its modifications.

Repro:
- log as User1 and load Asset1 preview in any playlist
- log as User2 from somewhere else (tested with icognito on chrome) and load the same Asset1 preview in any playlist
- User1 draws a square
- User2 draws a star
- User1 leaves the playlist (loading another asset preview in the same playlist is not enough)
- user1 load the asset preview in the playlist: he sees the star annotation but not the square annotation.

**Comment by frankrousseau** [comment]
Thank you for reporting. It's a complex case, not sure we can really fix this (or maybe that we should add a lock system) but at least we will have something it recorded here.

**Comment by dee909** [comment]
It's indeed complex and I do agree a lock wouldn't be a good UX.

Seeing [this](https://github.com/cgwire/zou/blob/0ce2508f7d85adf0c8986d8aa7c9832f237afe32/zou/app/models/preview_file.py#L33) you probably store annotation data in a serialized python object.
If that's the case, an option could be to store annotations per user: `{userId:annotation_data, userId:annotation_data}`

This would cost a read before each write. IDK if that's an issue but I guess it's possible to do since it's probably what the undo and redo buttons are doing, right ? ;)

**Comment by frankrousseau** [comment]
Yep attaching annotations to a user id could help to fix that. Thank you for the suggestion

**Comment by dee909** [comment]
You're welcome.

**Comment by frankrousseau** [comment]
Hello @dee909, we revamped the way annotations are stored. We now put an ID on every object and only saves the diff with previous annotations when a user does changes. It generates much fewer conflicts.

**Comment by dee909** [comment]
Awesome !
Good Game guys :)

Le mar. 14 sept. 2021 11:07, Frank Rousseau ***@***.***> a
écrit :
