### ISSUE TITLE
Possibilities to asynchronous ffmpeg process

### ISSUE THREAD

**Issue by fananimi** [cgwire/zou#326]
I have uploaded a 20Mb video in the comment section and it looks  `ffmpeg` takes a long time until my request is timeout.  My temporary solution is increasing the timeout settings on the nginx, but I think it is not a good solution.

One of good solution is make the `ffmpeg`  process is doing in the background or async process I mean.

This is just my opinion, maybe another person has another point of view or a better solution than mine.

This is my `ps` log:

`root        2274    1333 99 17:41 ?        00:08:46 ffmpeg -i /tmp/zou/4dbabf83-7e77-47e1-bfc3-ac1d979f18fa.mp4.tmp -map 0:v -map 0:a -f mp4 -b 28M -pix_fmt yuv420p -preset medium -r 24.00 -s 1878x1080 -vcodec libx264 -vsync passthrough /tmp/zou/4dbabf83-7e77-47e1-bfc3-ac1d979f18fa.mp`

and this one is the response on the client-side:

![Selection_046](https://user-images.githubusercontent.com/497424/109337804-f7ef9300-7897-11eb-9449-ad8e7cd9099b.png)

Thanks.

**Comment by frankrousseau** [comment]
Thank you for mentioning this subject.

You can already do that by setting up the job queue. It requires more work for configuration but it works: https://zou.cg-wire.com/jobs/
