### ISSUE TITLE
This Preview is broken

### ISSUE THREAD

**Issue by clarkjohn2989** [cgwire/zou#330]
There is an error in preview uploading after i updated from version 0.12.40 to 0.12.51
ffmpeg in zou accepting mp4 files without any problem, but MOV extenstion is giving error in encoding and show error in kitsu web ui that preview is broken

**Comment by LarsCawley** [comment]
@clarkjohn2989 do your movs have no soundtrack?  Try adding a soundtrack, as a workaround for now.  Adding a silent wav works for me while we wait for news.

**Comment by frankrousseau** [comment]
I think it's fixed. Can you update and try again?
