### ISSUE TITLE
cgwire/kitsu How to take backup I need 

### ISSUE THREAD

**Issue by fireflycg** [cgwire/zou#334]
Hello , i need to transfer my kitsuprojectdata to a new system to take backup & restore could you please explain how to take postgresql backup and preview folder please explain step by step

**Comment by frankrousseau** [comment]
You can get the database with the following command:

```
# Activate the virtualenv first and load environment variables
zou dump_database
```

The preview folder must be fully copied in your backup folder. 

To restore everything, you need to load the dump in your Postgres instance and copy the preview folder so the new location.

**Comment by fireflycg** [comment]
Hi, Thank for your quick response on my issue , I have taken zou dump_database backup and preview folder old database  . how to restore  zou database in  new location database please send any link for restore it will be needful

**Comment by frankrousseau** [comment]
I added a backup section to the documentation

**Comment by frankrousseau** [comment]
https://zou.cg-wire.com/backup/

**Comment by fireflycg** [comment]
Hi, Thank for your time & suggestion, I had taken zou dump_database backup file format is getting 2021-03-23-zou-db-backup.dump  while pg_restore getting error is ( input file appears to be a text format dump. please use psql.)  

I am not getting this format : The generated file name will follow this format: 2021-03-21-zou-db-backup.sql.gz

**Comment by frankrousseau** [comment]
Please update Zou before trying to use the tutorial.

**Comment by fireflycg** [comment]
Hi Sir,
After updating zou The file format comes
2021-03-26-zou-db-backup.sql.gz,but when i restore with pg_restore -h
192.168.1.134 -p 5432 -U postgres -d targetdb 2021-03-26-zou-db-backup.sql
pg_restore: error: input file appears to be a text format dump. Please use
psql. this error coming

**Comment by fireflycg** [comment]
Hi Sir,
After updating zou The file format comes
2021-03-26-zou-db-backup.sql.gz,but when i restore with pg_restore -h
CGWIRE -p 5432 -U postgres -d targetdb 2021-03-26-zou-db-backup.sql
pg_restore: error: input file appears to be a text format dump. Please use
psql. this error coming

**Comment by frankrousseau** [comment]
Can you try to use `psql` instead of `pg_restore`?

**Comment by fireflycg** [comment]
Hi,
I have used with psql for pg_restore but how should i switch database to zoudb to targetdb after restore i am unable to view my backup after login into kitsu

**Comment by frankrousseau** [comment]
All environment variables needed to configure the database are listed there:

https://zou.cg-wire.com/configuration/

**Comment by frankrousseau** [comment]
You should restore directly to `zoudb` instead of `targetdb`. Elsewhere, you have to use the environment variable to use `targetdb` instead of default `zoudb`.
