### ISSUE TITLE
Project models can be accessed by any user through REST api

### ISSUE THREAD

**Issue by mathbou** [cgwire/zou#338]
Issue:

Project datas can be queried by any user by using query strings. The problem occurs regardless of the permission level.

`kitsu.local/api/data/projects/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX` returns a permission error as intended

`kitsu.local/api/data/projects?id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX` returns the project

Cg-Wire version: Kitsu 0.12.57 // Zou 0.12.57

**Comment by frankrousseau** [comment]
Thank you for reporting. 
I had to rewrite the title of the issue. Because it was confusing and could create misunderstanding.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
