### ISSUE TITLE
Cg Wire Kitsu

### ISSUE THREAD

**Issue by sudhakargoud** [cgwire/zou#340]
Hi Sir,
I have dump zou data_base backup,i got backup  2021-04-05-zou-db-backup.sql.gz format,,how to restore in new system with psql command can you please share step by step it will be helpfull
Thank you

**Comment by sudhakargoud** [comment]
Hi Sir,
when i am creating zou admin user error below

zou create-admin adminemail@yourstudio.com
Usage: zou create-admin [OPTIONS] EMAIL
Try 'zou create-admin --help' for help.

Error: Missing option '--password'.

**Comment by EvanBldy** [comment]
Hi @sudhakargoud, I close because it's a duplicate from https://github.com/cgwire/zou/issues/560
