### ISSUE TITLE
Can't create project on a fresh installation of Kitsu with Chrome

### ISSUE THREAD

**Issue by stephRipe** [cgwire/zou#341]
Hello,
I've tried to create a project with Chrome and I've got this feedbacks:
"An error occurred while editing production. Please contact our support team."
Logs :2021-03-28 22:47:38NEWproject
user
SA
Super Admin
project_id 0d7f067b-a045-4882-9284-82483338ddc8

Then I've made a request on Zou with Gazu and I've got the list of the projects that I've tried to create previously.

So I've logged to Kitsu with firefox. 
I can't see my previous projects, the creation of new projects with Firefox worked fine.

I've logged again with Chrome, I can see the projects that I created with Firefox.
My conclusion : is creation of projects is possible with Firefox, but not complete with chrome.

Maybe take a look at the project_status_id...
extracted from zou with gazu :
WITH FIREFOX
{'id': '7ef94d0c-35b6-431e-9f51-c141d743d579', 'created_at': '2021-03-28T21:40:58', 'updated_at': '2021-03-28T21:40:58', 'name': 'projet firefox', 'code': None, 'description': None, 'shotgun_id': None, 'file_tree': None, 'data': None, 'has_avatar': False, 'fps': None, 'ratio': None, 'resolution': None, 'production_type': 'short', 'start_date': None, 'end_date': None, 'man_days': None, 'nb_episodes': 0, 'episode_span': 0, 'project_status_id': 'ec08fdce-55d5-4e00-a17b-0b1eee60dbb1', 'type': 'Project'}
WITH CHROME
{'id': '44bb676e-bfe7-4dfe-86de-34ca4ef10909', 'created_at': '2021-03-28T20:22:41', 'updated_at': '2021-03-28T20:22:41', 'name': 'projet chrome', 'code': None, 'description': None, 'shotgun_id': None, 'file_tree': None, 'data': None, 'has_avatar': False, 'fps': None, 'ratio': None, 'resolution': None, 'production_type': 'short', 'start_date': None, 'end_date': None, 'man_days': None, 'nb_episodes': 0, 'episode_span': 0, 'project_status_id': None, 'type': 'Project'}

CONFIGURATION:
On a fresh installation of Kitsu (0.12.57) on a ubuntu 20.10 on a raspberry pi 4 with 8Go RAM.

**Comment by frankrousseau** [comment]
Sorry, I can't reproduce your bug. Please verify that your installation is properly running by accessing this URL : `http://localhost:5000/api/status` and see if you find an answer in the troubleshooting section: https://zou.cg-wire.com/troubleshooting/
