### ISSUE TITLE
cgwire-Kitsu 

### ISSUE THREAD

**Issue by sudhakargoud** [cgwire/zou#342]
Hi kitsu,  In Time sheet  how to enable weekends (Saturday,Sunday )

**Comment by sudhakargoud** [comment]
Hi kitsu, In Time sheet how to enable weekends (Saturday,Sunday ) @frankrousseau please address this

**Comment by frankrousseau** [comment]
Hello @sudhakargoud,
You can alreday set time in timesheets during the weekend.

**Comment by frankrousseau** [comment]
And please write a proper title, it will make things clearer for the community.
