### ISSUE TITLE
database not up

### ISSUE THREAD

**Issue by tpolson** [cgwire/zou#345]
I have run through the install process on Ubuntu 20.  I believe everything is working except connecting to the database.

API status

name | "Zou"
-- | --
version | "0.12.70"
database-up | false
key-value-store-up | true
event-stream-up | true
job-queue-up | false

You have a brief section on configuration, but I am not clear which file to add the database and email config info.  Is that the /etc/systemd/system/zou.service file?

Thanks

**Comment by frankrousseau** [comment]
Yes, you should add the variables to the `zou.service` file.

**Comment by frankrousseau** [comment]
I close this due to inactivity.
