### ISSUE TITLE
This preview is broken

### ISSUE THREAD

**Issue by aixzhou0216** [cgwire/zou#353]
I uploaded some videos,whatever mp4 or mov,showing this error
![image](https://user-images.githubusercontent.com/82997546/120463658-b73f7280-c3ce-11eb-97ed-bed14341dcc2.png)
I checked gunicorn_error.log
`[2021-06-02 17:55:15,605] ERROR in preview_files_service: b"ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv\n  libavutil      54. 31.100 / 54. 31.100\n  libavcodec     56. 60.100 / 56. 60.100\n  libavformat    56. 40.101 / 56. 40.101\n  libavdevice    56.  4.100 / 56.  4.100\n  libavfilter     5. 40.101 /  5. 40.101\n  libavresample   2.  1.  0 /  2.  1.  0\n  libswscale      3.  1.101 /  3.  1.101\n  libswresample   1.  2.101 /  1.  2.101\n  libpostproc    53.  3.100 / 53.  3.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/zou/2ff4a31a-d35f-4a40-ad5f-44b17068b36f.mp4.tmp':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.29.100\n  Duration: 00:00:04.88, start: 0.000000, bitrate: 738 kb/s\n    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 531 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\n    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 193 kb/s (default)\n    Metadata:\n      handler_name    : SoundHandler\nPlease use -b:a or -b:v, -b is ambiguous\n[libx264 @ 0x173b8e0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2\n[libx264 @ 0x173b8e0] profile High, level 5.0\n[libx264 @ 0x173b8e0] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=umh subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=abr mbtree=1 bitrate=28000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\n[aac @ 0x1705ba0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.\n[libx264 @ 0x173b8e0] final ratefactor: 2.70\n"`
`[2021-06-02 17:55:15,606] ERROR in preview_files_service: failed`
**`Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/services/preview_files_service.py", line 99, in prepare_and_store_movie
    uploaded_movie_path, fps=fps, width=width, height=height
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/utils/movie.py", line 109, in normalize_movie
    stream.run(quiet=False, capture_stderr=True, overwrite_output=True)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)`**

Thanks for your help

**Comment by aixzhou0216** [comment]
Use these commands
`sudo add-apt-repository ppa:jonathonf/ffmpeg-4`
`sudo apt-get update`
`sudo apt-get install ffmpeg`
works for me.

**Comment by coolturens** [comment]
I have the same issue, I tried aixzhou0216 solution but still not working, I tried with .mov and avi too. I can see .jpg but not video.

[2022-02-22 09:56:44,939] ERROR in preview_files_service: failed
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/preview_files_service.py", line 148, in prepare_and_store_movie
    ) = movie.normalize_movie(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/utils/movie.py", line 144, in normalize_movie
    raise (e)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/utils/movie.py", line 141, in normalize_movie
    stream.run(quiet=False, capture_stderr=True, overwrite_output=True)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
[2022-02-22 09:56:45,301] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/files/previews/3f0/d9e/3f0d9edd-b783-450a-bf15-608fe557d344'
[2022-02-22 09:56:45,301] ERROR in resources: Non-movie file was not found for: 3f0d9edd-b783-450a-bf15-608fe557d344
