### ISSUE TITLE
Push updated docs to zou.cg-wire.com

### ISSUE THREAD

**Issue by fsiddi** [cgwire/zou#354]
It looks like the latest version of the zou docs were not pushed to https://zou.cg-wire.com/api/.
Pushing the updated docs would prevent confusion as the API paths in the doc examples are currently incorrect (possibly outdated).

**Comment by frankrousseau** [comment]
Mmm, it's just that we don't really maintain this section. I would like to use a doc generator for the API. But I haven't found the time to implement it.

**Comment by fsiddi** [comment]
Would making a GH automation help? This should be pretty straight forward nowadays. If it's a matter of writing a GH action that builds the docs and pushes them to the server I can help out.

**Comment by frankrousseau** [comment]
The documentation is already deployed on any change. But the API section hasn't been updated for a while.

**Comment by frankrousseau** [comment]
There is a Netlify integration.

**Comment by fsiddi** [comment]
Just to be clearer on the issue I'm experiencing:

* Visit https://zou.cg-wire.com/api/
* Click *Edit on Zou*
* You'll load https://github.com/cgwire/zou/edit/docs/docs/api.md, whose content is different than what you can see on the site

If the docs are deployed on change, how can the page in production not match the source?

**Comment by frankrousseau** [comment]
Ok we had problems with the deployment. It should be fixed now.

**Comment by fsiddi** [comment]
Fantastic, thanks a lot!
