### ISSUE TITLE
Possible data desync between Kitsu UI and web API

### ISSUE THREAD

**Issue by LedruRollin** [cgwire/zou#359]
Hi !

We encountered a bug involving a playlist. In the Kitsu UI, the playlist has 11 distinct shots. However on the web API side (.../api/data/playlists/<playlist_id>), it contains 15 shots. See the actual result of the request : [wrong_playlist.txt](https://github.com/cgwire/zou/files/6855754/wrong_playlist.txt) ; the 4 additional shots are actually duplicates of the first four shots of the playlist. 
To illustrate, if we use gazu to retrieve the shots, we get this : 

![image](https://user-images.githubusercontent.com/32680314/126491462-ca61302b-994b-42e0-bf4c-7ff36b927c95.png)

We've not found this bug in any other playlist, and we don't know what could have caused this error. It's not a critical error (we can just recreate another playlist), but it highlights some kind of desynchronisation between the front and the back. Let me know if you want any additional detail, especially if other users encounter a similar issue

**Comment by frankrousseau** [comment]
It's too hard to reproduce. I close the issue. Feel free to open it again if needed. Whatever the information is stored by GIthub.
