### ISSUE TITLE
"job-queue-up": false 

### ISSUE THREAD

**Issue by Animatect** [cgwire/zou#364]
Hi, when I run http://localhost/api/status I get:
{
  "name": "Zou", 
  "version": "0.13.2", 
  "database-up": true, 
  "key-value-store-up": true, 
  "event-stream-up": true, 
  "job-queue-up": false
}
I know it has to do with zou-rq service but I really don't know how to get it up, I think this is related to why I can't send mails from kitsu, because as far as I've tested I can create users, shots, etc.
Softare seems amazing btw :)

**Comment by frankrousseau** [comment]
Hello Animatect,
To set up the job queue you can refer to the documentation but it's not mandatory to make Kitsu working: https://zou.cg-wire.com/jobs.html 
For your email problem make sure that your email provider doesn't block them.

**Comment by Animatect** [comment]
I'll take a look tonight, thanks so much!

**Comment by Animatect** [comment]
Hey Frank, You were dead on about the email problem, it is working great now, thank you so much.
I also got the jobs service running, thank you for this too, I would like to add a small note, I think it might be evident but on the documentation for jobs which is really well laid out I would at the end add that is necessary to start the service.  

sudo service zou-jobs start

one last question just to be sure, when the documentation references the main service file, it is refering to zou.service am I right?.

Again Thank you. :)

**Comment by frankrousseau** [comment]
> I would at the end add that is necessary to start the service.

Can you contribute to the documentation?

> one last question just to be sure, when the documentation references the main service file, it is refering to zou.service am I right?.
Yes it is.

**Comment by Animatect** [comment]
Hey frank, I did a pull request with the changes, I got mixed up and didn't change the name, sorry it should be called "Patch 1"

**Comment by frankrousseau** [comment]
Great, thank you!
