### ISSUE TITLE
File tree variable <Department> not working for output files

### ISSUE THREAD

**Issue by Plyrolith** [cgwire/zou#397]
\<Department> is currently only working for building work file paths.
Could be easily fixed by expanding the parameters of **get_folder_from_department** and extend that function to directly grab the department id from the task type there using an if switch, just like the function a few lines below.

https://github.com/cgwire/zou/blob/98dce8145db13f8559d43b0d68d3a6299554f2b6/zou/app/services/file_tree_service.py#L543

Edit to:

```python
def get_folder_from_department(task, task_type, field):
    if task_type is None and task is not None:
        department = tasks_service.get_department_from_task(task["id"])
        folder = department[field]
    elif task_type is not None:
        task_type = get_task_type_raw(task_type["id"])
        department = get_department(task_type.department_id)
        folder = department[field]
    return folder
```

or put it in a new *get_department_from_task_type* function for consistency.

This would be really helpful for completely partitioning production folders to synchronize only certain departments with other studios.

Thanks!

**Comment by frankrousseau** [comment]
Thank you for the bug report. Do you think that you could handle it and make a PR for this?

**Comment by Plyrolith** [comment]
Will do! I'll set it up until the end of the week.
