### ISSUE TITLE
'zou' not foud

### ISSUE THREAD

**Issue by 4nker** [cgwire/zou#399]
During installation on Ubuntu (20.04.3 LTS) when running the following command:

Finally, create database tables (it is required to leave the posgres console and to activate the Zou virtual environment):

Run it in your bash console.
**DB_PASSWORD=yourdbpassword zou init-db**

The output is **"Command 'zou' not found, did you mean:"**

I have also tried this install process multiple times on Pop-OS. The error is the same each time. I have replaced "yourdbpassword" with the actual db password.

**Comment by frankrousseau** [comment]
Hello @4nker, thank you for your interest in Kitsu, this message means that you didn't activate the virtual environment.

```
. /opt/zou/zouenv/bin/activate
```

**Comment by 4nker** [comment]
Ok. Thanks for the quick reply. I will re-run the install and pay special attention to this step and feedback.

**Comment by 4nker** [comment]
running ". /opt/zou/zouenv/bin/activate"    instead of  ". zouenv/bin/activate" worked. Everything is up and running now. Not sure why it didn't work as everything was where it should be. Thanks for your assistance.

**Comment by frankrousseau** [comment]
Great, you can enjoy Kitsu now!
