### ISSUE TITLE
Task Type for_entity field is wrong

### ISSUE THREAD

**Issue by johhnry** [cgwire/zou#403]
Hi,

I am using Zou `0.13.23` and I have a task type like the following (displayed in Kitsu):

![image](https://user-images.githubusercontent.com/35373357/144662157-253923e4-2b23-4fd4-8d73-12f28b32ca12.png)

However when querying `/api/data/task-types`, the `for_entity` field is indicating `Asset` instead of `Shot`:

```json
{
  "id": "9d14f3e6-b389-4a5a-b3c3-d18dcad25e7f",
  "created_at": "2021-10-27T13:46:35",
  "updated_at": "2021-11-19T20:30:59",
  "name": "Storyboard",
  "short_name": "",
  "color": "#43A047",
  "priority": 1,
  "for_shots": true,
  "for_entity": "Asset",
  "allow_timelog": true,
  "shotgun_id": null,
  "department_id": "6139543a-7f7c-4b4e-9e32-3437d8520ede",
  "type": "TaskType"
},
```

I can use the `for_shots` to differentiate if the task is on an asset or a shot but what if we have tasks at the sequence level?

Thanks!

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by johhnry** [comment]
Thanks @frankrousseau, it works now in Zou 0.13.45!

I got:

```json
{
  "name": "Storyboard",
  "for_shots": true,
  "for_entity": "Shot",
  "type": "TaskType"
}
```
