### ISSUE TITLE
`alembic_version` still exist after `zou clear-db` 

### ISSUE THREAD

**Issue by nledez** [cgwire/zou#405]
Hi, when you launch `zou clear-db` the table `alembic_version` still exists and filled with the last migration.

With this table and `version_num` defined the command `zou init-db` do noting.

To reproduce:
- Launch `zou init-db` to have a fresh DB
- In Postgres `\d` list all tables
- Launch `zou clear-db` to clean the DB
- In Postgres `\d` show `alembic_version` table that remains
- `select * from alembic_version;` show the last `version_num`
- Launch `zou init-db`

```
Creating database and tables...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Database and tables created.
```

**Comment by frankrousseau** [comment]
You're right, it's not optimal. You have to run the `zou reset-migrations` command.

**Comment by frankrousseau** [comment]
@nledez Can I Close this issue?
