### ISSUE TITLE
Can't able to perform backup

### ISSUE THREAD

**Issue by codersaran** [cgwire/zou#406]
I was trying to backup using the code
cd /opt/zou
. zouenv/bin/activate
DB_PASSWORD=yourdbpassword zou dump-database
I was running myself kitsu in ubuntu 20.04

but the dump-data base result in the permission denied.

**Comment by frankrousseau** [comment]
Hello @codersaran,

Thank you for the report. You must check that you have the rights to write in the working directory.

**Comment by codersaran** [comment]
![Screenshot from 2022-01-14 18-59-32](https://user-images.githubusercontent.com/49817946/149528040-9ab5adfa-4860-464b-bde9-4b1dd11b7d1a.png)
![Screenshot from 2022-01-14 19-00-16](https://user-images.githubusercontent.com/49817946/149528045-cca6e03f-9f59-4dea-acfc-f2064f7b98d3.png)
I think that the zou has permission to write in the /opt/zou directory unless if it is not writing in that directory the permission would have denied. I can't find actually where it is trying to save the backup file.

**Comment by frankrousseau** [comment]
I think it saves it in your current directory.

**Comment by codersaran** [comment]
Yes i think so.I got away from this issue by directly backing up from the postgres and again restoring it back through postgres itself without entering zou.
