### ISSUE TITLE
Custom metadata for shot casting

### ISSUE THREAD

**Issue by paulgolter** [cgwire/zou#408]
Hey 🙂

As requested by @frankrousseau in the Discord channel, I create an issue for this feature request here. 

It would be great if we could add some custom metadata to the casting entries of the shot, e.G what version of the asset is being casted. 
It would be sufficient to allow TDs to store data in the known `data={}` dictionary for each asset entry in the shot casting.

So I would need to do something like this: 

```
# Get casting for shot.
shot_casting = gazu.casting.get_shot_casting(shot)

# Add metadata.
for asset_entry in shot_casting:
    asset_entry["data"] = {"version": asset_version}

# Update shot casting. 
gazu.casting.update_shot_casting(project, shot, shot_casting)
```

**Comment by frankrousseau** [comment]
Thank you Paul for the suggestion. We'll see what we can do for this

**Comment by frankrousseau** [comment]
We added the field to the links. But I'm not sure that it will be enough for you. Can you try if you can do something with it?
