### ISSUE TITLE
Disabled AD users always set as active in Zou

### ISSUE THREAD

**Issue by mathbou** [cgwire/zou#417]
The state of our users are no longer taken into account when syncing our AD. It seems 497c007 introduced the regression.

Cg-Wire version: Kitsu 0.13.42 // Zou 0.13.27

**Comment by frankrousseau** [comment]
Thank you for reporting. It's weird because the code doesn't match the commit message.

**Comment by mathbou** [comment]
Resolved by 09ce62f6df449fee8f58bd6bad0d945a834dd1f3
