### ISSUE TITLE
during installation: Cannot access to the required Redis instance

### ISSUE THREAD

**Issue by jmreymond** [cgwire/zou#466]
I am trying to install the software.
I have created a PostgreSQL database on another server and I can access the database:
`psql -h 10.0.3.1 -U postgres  zoudb
psql (12.10 (Ubuntu 12.10-0ubuntu0.20.04.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

zoudb=# \q
`
but next step is to configure database:
`# DB_HOST=10.0.3.1 zou init-db
Cannot access to the required Redis instance`
no more error message: what's wrong ?
I cannot find a log file.
Any tips ?
thanks,

**Comment by frankrousseau** [comment]
Hello @jmreymond,
The error message tells that the Redis instance is not up. I think you should look what is wrong the Redis installation.

**Comment by jmreymond** [comment]
Hi
I am following the documentation and in the chapter "Prepare database"
"Prepare key value store" is the next chapter.
Does it mean that the order is not correct ?

**Comment by jmreymond** [comment]
so, I have changed the config file for redis and now, it works like a charm
thanks
