### ISSUE TITLE
Allow users to override default configuration

### ISSUE THREAD

**Issue by pilou-** [cgwire/zou#47]
Call to `app.config.from_envvar` was removed in 3a69d1ccb264e4f9de57a906a5b2d89b45421426, but this call allowed users to override default values defined in [`zou/app/config.py`](https://github.com/cgwire/zou/blob/master/zou/app/config.py) - for example `KEY_VALUE_STORE` or `NB_RECORDS_PER_PAGE` - using a custom configuration Python file.

**Comment by frankrousseau** [comment]
Thanks for reporting!

**Comment by frankrousseau** [comment]
It was fixed in last version. I close this one. Feel free to reopen it if needed!
