### ISSUE TITLE
Improve plugins mechanism

### ISSUE THREAD

**Issue by pilou-** [cgwire/zou#48]
Zou try to import [`event_handlers`](https://github.com/cgwire/zou/blob/master/zou/app/api.py#L57) (module name is hardcoded). By default, this work only when the current working directory contains such a module - this is the case when current working directory is the source directory.

Instead of importing `event_handlers`, another mechanism should be used, [for example](https://packaging.python.org/guides/creating-and-discovering-plugins/).

**Comment by frankrousseau** [comment]
Thanks for reporting!

**Comment by frankrousseau** [comment]
https://cgwire.canny.io/integration/p/create-a-plugin-system

**Comment by BigRoy** [comment]
For what it's worth, I always loved the flexibility and simplicity of how [Pyblish discovers plug-ins](https://github.com/pyblish/pyblish-base/blob/3290fd5b51b496d431cc2ca608639e21e727ccbd/pyblish/plugin.py#L1281-L1381). It's simple yet flexible enough to be usable across many different use cases.

Just inherit from Pyblish' `Plugin` class and put that `.py` somewhere on a path that `discover()` knows about. [The same is used in Avalon for discovering its plugins](https://github.com/getavalon/core/blob/0e3b5742041e6018a4d889cb4e771263f0a79a55/avalon/pipeline.py#L472-L493) allowing multiple Plugins to be differentiated from each other.

```python
# pseudo code 
for plugin in api.discover(api.Plugin):
    # do what you want with all the plugins
    plugin.run()
```
