### ISSUE TITLE
Environment variable was not working when I used "zou sync-with-ldap-server" command?

### ISSUE THREAD

**Issue by apollojph** [cgwire/zou#480]
When I used `zou sync-with-ldap-server` command in the [LDAP document](https://zou.cg-wire.com/ldap/#user-list-synchronization), it showed `ldap3.core.exceptions.LDAPInvalidDNSyntaxResult: LDAPInvalidDNSyntaxResult - 34 - invalidDNSyntax - None - invalid DN - bindResponse - None`.

Here's the screenshot about error message:

![20220608_kitsu_ldap_1](https://user-images.githubusercontent.com/17536468/172581538-77eb6ae6-d94b-4bcc-83bf-cbf2fabff237.png)

Here's my `/etc/systemd/system/zou.service` settings:
```
[Unit]
Description=Gunicorn instance to serve the Zou API
After=network.target

[Service]
User=zou
Group=www-data
WorkingDirectory=/opt/zou
# Append DB_USERNAME=username DB_HOST=server when default values aren't used
# ffmpeg must be in PATH
Environment="DB_PASSWORD=yourpassword"
Environment="SECRET_KEY=yourkey"
Environment="PATH=/opt/zou/zouenv/bin:/usr/bin"
Environment="PREVIEW_FOLDER=/opt/zou/previews"
Environment="TMP_DIR=/opt/zou/tmp"
Environment="AUTH_STRATEGY=auth_remote_ldap"
Environment="LDAP_HOST=ldaps://ldap.jumpcloud.com"
Environment="LDAP_PORT=636"
Environment="LDAP_BASE_DN=ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com"
Environment="LDAP_DOMAIN=ldaps://ldap.jumpcloud.com"
Environment="LDAP_FALLBACK=True"
Environment="LDAP_USER=your_ldap_username"
Environment="LDAP_PASSWORD=your_ldap_password"
Environment="LDAP_EMAIL_DOMAIN=your_domain"
Environment="LDAP_EXCLUDED_ACCOUNTS=Administrator,TestAccount"
ExecStart=/opt/zou/zouenv/bin/gunicorn  -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app

[Install]
WantedBy=multi-user.target
```

I tried many times but it didn't work. So, I changed these two file's default value:
`/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/config.py`

![20220608_kitsu_ldap_2](https://user-images.githubusercontent.com/17536468/172584987-e362ebc2-4807-4a98-84d0-1eeb4e3cd89f.png)

`/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/utils/commands.py`

![20220608_kitsu_ldap_3](https://user-images.githubusercontent.com/17536468/172585007-b57ca6c7-1e47-417a-8c78-455f4d95a602.png)

I did `zou sync-with-ldap-server` again and it works!!
Is the `os.getenv` not working?
Thanks

**Comment by frankrousseau** [comment]
It works as expected. It's just that you have to add this command on the command line or load a `.env` file. Examples:

```
LDAP_HOST=myldap.mystudio.com zou ldap-sync
```


```
source zou.env
zou ldap-sync
```

`zou.env` looks like:
```
export LDAP_HOST=myldap.mystudio.com 
```
