### ISSUE TITLE
Can I set the default timezone and locale?

### ISSUE THREAD

**Issue by fyplclfkr** [cgwire/zou#485]
When I create a new user, the default time zone is Paris and the language is English. Can I change the default？

**Comment by EvanBldy** [comment]
Hi @fyplclfkr!
For the timezone there's this environment variable that can be set : https://github.com/cgwire/zou/blob/bd477a44a30d4f16659b2228d0a9458f6a2d77bd/zou/app/config.py#L128
For the default language it's not possible to change the default that is Locale("en", "US") for the moment.
