### ISSUE TITLE
Zou commands raise error `Permission denied: 'indexes'` on each call

### ISSUE THREAD

**Issue by nledez** [cgwire/zou#491]
If you aren't in `/opt/zou` folder and not with user `zou` commands (`init-db`, `upgrade-db`, `create-admin` and `init-data` for now).

**Comment by frankrousseau** [comment]
You have to set the `INDEXES_FOLDER` variable to the folder you want to avoid this problem.

**Comment by nledez** [comment]
Nope. But it’s not in documentation.
(in old doc - maybe use by other users):
’DB_PASSWORD=yourdbpassword zou upgrade-db ’
It’s failed with ’Permission denied’ error. Or it creates a ’indexes’ folder on the current path (wrong one).

**Comment by gstorni** [comment]
Hello, I got the same issue trying to backup the database
<img width="844" alt="Screen Shot 2022-07-07 at 22 43 50" src="https://user-images.githubusercontent.com/3090235/177899965-aa80c5ca-3798-4a01-b9b7-a71fb5bfc5d0.png">

I found this waklkaround. 
https://stackoverflow.com/questions/67863292/permissionerror-errno-13-permission-denied-on-ubuntu-trying-to-run-selenium

"sudo chmod -R 777 /path/to/gecko"

and it worked.
<img width="1004" alt="Screen Shot 2022-07-07 at 22 51 14" src="https://user-images.githubusercontent.com/3090235/177900609-0da6f8c4-168f-49a0-a4a2-d9ddfacf1a53.png">

It happend the same in a Google Cloud Ubuntu Instance with Postgresql localhost and locally in a Multipass Ubuntu Instance with the database in another instance.

Hope it helps!

**Comment by frankrousseau** [comment]
Please don't do that. It gives access rights to everyone.  A `chown` for the `zou` user should be enough.

**Comment by gstorni** [comment]
Thank you Frank, Ill try that.

**Comment by EvanBldy** [comment]
Hi @nledez,
It should be fixed in this PR https://github.com/cgwire/zou/pull/520
