### ISSUE TITLE
After restoring to new database, backup command continues to dump old database.

### ISSUE THREAD

**Issue by flinfo** [cgwire/zou#496]
I had done a clone of our kitsu server, just in case our main server fell over... which it just did. I simply restored the latest database backup to the clone. (including preview folder).
So 'zoudb' was the database, and the latest backup was restored to a new database called 'zoudb3'.
I updated /etc/systemd/system/zou.service to include the DB_DATABASE reference like so:
`Environment="DB_DATABASE=zoudb3"`

That worked perfectly. Kitsu running again like nothing happened, except now when I run:

`DB_PASSWORD=yourdbpassword zou dump-database`

it seems to still be backing up the old, outdated, database at the point it was cloned months ago (as zoudb still exists)

Should this automatically be referencing the new database in use, or is there something else I need to change also?

**Comment by frankrousseau** [comment]
You have to give the database name too through the environment variables. 

```
DB_DATABASE=zoudb3 DB_PASSWORD=yourdbpassword zou dump-database
```

**Comment by flinfo** [comment]
That worked perfectly. "Of course!" came to mind when I read it. Thanks 👍
