### ISSUE TITLE
zou-jobs running very slow on Synology NAS DS920+

### ISSUE THREAD

**Issue by gregoiredelzongle** [cgwire/zou#498]
Hey everyone and thank you for this amazing software.

I run zou+kitsu using the [https://gitlab.com/mathbou/docker-cgwire](Mathieu BOUZARD dockerized version).
Everything works well but the docker contenair which is running zou-jobs is eating all the ram and cpu power, slowing down all other process running inside the NAS (which is 4GB ram and a intel 4core at 2ghz). It may be better to switch to a dedicated hardware to  perform this task, but I dont know much about the minimum requirements it needs to process the jobs, or if I can change zou configuration to avoid issues.

Thank you !

**Comment by frankrousseau** [comment]
Hello @gregoiredelzongle, it depends on your needs. If you upload short shots it should be ok. We use FFMPEG to normalize all uploaded videos. But it eats up everything it can. So, if you face slowness you can look at limiting the resource available for the job's container.

**Comment by gregoiredelzongle** [comment]
I was able to limit the cpu and ram usage by adding some rules to the docker-compose file, it's slow but it works !
