### ISSUE TITLE
Can multiple folders with fixed names be generated at the end of the file path

### ISSUE THREAD

**Issue by fyplclfkr** [cgwire/zou#501]
![image](https://user-images.githubusercontent.com/74193811/179016668-f0630a46-fa35-481b-bf0d-5f41553b406e.png)

I want to create three folders in the folder of animation tasks, which are the same as those in the pictures. Is it possible? How should I set up my file tree? Thank you very much. If I can't, I can only build it manually.

**Comment by frankrousseau** [comment]
You can have several modes, by adding entries like "output" similar as the working file entry you have.
Then when you build your file path, you have to give the mode as parameter of the `build_path` function.
