### ISSUE TITLE
LDAP filter

### ISSUE THREAD

**Issue by kapellan2000** [cgwire/zou#528]
Hi,
Please tell me how can I use LDAP filter to sync only required accounts.
I can use "LDAP_EXCLUDED_ACCOUNTS=Administrator,TestAccount \" to exclude users
Maybe there is something for groups, filters, etc.?

**Comment by EvanBldy** [comment]
Hi @kapellan2000,
I'm sorry this is not possible for the moment you can only use "LDAP_EXCLUDED_ACCOUNTS", maybe you can use LDAP_GROUP if your LDAP is an AD ? It will import only users in this group.
