### ISSUE TITLE
LDAP: use of a unpopulated attribute for authentication, impossibility to connect.

### ISSUE THREAD

**Issue by autoiue** [cgwire/zou#540]
In the file [auth_service.py line 121](https://github.com/cgwire/zou/blob/e8c9cd3069a833fa36ea6822b390c03365f21446/zou/app/services/auth_service.py#L121), the attribute `full_name `of the `person` object does not exist.

This leads to a bad value being used for authentificatino against the LDAP server.

Replacing `full_name` by `desktop_login` seems to work.

See pull request #541

**Comment by EvanBldy** [comment]
Hi @procsynth,
As I said in your PR full_name it's a calculated value from the first and last name. See here : https://github.com/cgwire/zou/blob/ece10754ded8617f63a206fb538d2ace9312f811/zou/app/models/person.py#L73

Are you trying to connect with Administrator account ? 
He doesn't have a first name (givenName) and last_name (sn) so it can't work. I will fix that.

**Comment by EvanBldy** [comment]
It was fixed for Administrator in this PR : https://github.com/cgwire/zou/pull/547

**Comment by frankrousseau** [comment]
@procsynth could you confirm it was fixed?
