### ISSUE TITLE
Kitsu Error

### ISSUE THREAD

**Issue by sudhakargoud** [cgwire/zou#560]
@frankrousseau 
Hi Sir,

Cg wire kits getting error
when am creating admin user following error

bin/zou create-admin [adminemail@ffstudio.in](mailto:adminemail@ffstudio.in)
Usage: zou create-admin [OPTIONS] EMAIL
Try 'zou create-admin --help' for help.

Error: Missing option '--password'.

**Comment by EvanBldy** [comment]
Hi @sudhakargoud, 
You need to set the password for this admin (it was "default", we removed this) : 
`zou create-admin youremail --password "yourpassword"`

**Comment by sudhakargoud** [comment]
> Hi @sudhakargoud, You need to set the password for this admin (it was "default", we removed this) : `zou create-admin youremail --password "yourpassword"`

Hi @EvanBldy 

Thanks sir 

its worked fine
