### ISSUE TITLE
Hi Sir,

### ISSUE THREAD

**Issue by sudhakargoud** [cgwire/zou#562]
Hi Sir,
when i am creating zou admin user error below

zou create-admin adminemail@yourstudio.com
Usage: zou create-admin [OPTIONS] EMAIL
Try 'zou create-admin --help' for help.

Error: Missing option '--password'.

_Originally posted by @sudhakargoud in https://github.com/cgwire/zou/issues/340#issuecomment-1350551750_

**Comment by EvanBldy** [comment]
Hi @sudhakargoud I close because it's a duplicate from https://github.com/cgwire/zou/issues/560.

**Comment by sudhakargoud** [comment]
Hi @EvanBldy 

Hi Sir,

how to restore in new system with psql command can you please share step by step it will be helpfull.Backup restore point not working

Thank you
