### ISSUE TITLE
Backup & Restore 

### ISSUE THREAD

**Issue by sudhakargoud** [cgwire/zou#563]
Hi @EvanBldy 
Hi Sir,

How to restore in new system with psql command can you please share step by step it will be helpfully.Backup Restore not working

Thank you

**Comment by frankrousseau** [comment]
You will find all information here: https://zou.cg-wire.com/backup/

**Comment by sudhakargoud** [comment]
Hi @frankrousseau 

its not working
in psql 

psql zoudb < /opt/zou/2022-12-22-zou-db-backup.sql
its restoring but db not showing
