### ISSUE TITLE
Restore 

### ISSUE THREAD

**Issue by sudhakargoud** [cgwire/zou#565]
Hi @frankrousseau

its not working sir

in psql i am restoring below 
psql zoudb < /opt/zou/2022-12-22-zou-db-backup.sql
its restoring but db not showing
Previous 2 year back i restored like this its worked fine,but now its not working

**Comment by Animatect** [comment]
I'm having the same problem, I thought that I was doing something wrong,.

**Comment by frankrousseau** [comment]
The documentation was updated. Thank you @Animatect

**Comment by sudhakargoud** [comment]
> Ok solved it, it was a matter of making sure that source zou and target zou are the same version so there is no discrepancies on the schemas, I'm going to propose a small update to the documentation.

@Animatect  Hi same problem its restored but not working Log in failed, please verify your credentials. 
i have to install same version zou in new system also?
