### ISSUE TITLE
can't set previews folder on mounted drive

### ISSUE THREAD

**Issue by Animatect** [cgwire/zou#572]
Hi, this is not an issue with zou and it derives 100% from my inexperience working with Linux, I'm posting it here anyway since if it gets solved it will probably help someone else with the same problem, if this is not the place to ask such question please let me know and I'll be happy to remove it.

I've been using kitsu for a year now and the drive where it is installed is now full. I want to either mount a second drive or mount a location on my synology server, but when I reassign the path in the global variables it works flawlessly if the location is onthe same drive, but in other drives (/mount/user/....) it gives me a permissions error, even though I assigned zou as the user and the appropiate group is assigned to all the folders on the new drive too.
Is there something I should do so zou does not have these permission errors?

I've also noticed that the files that were already created in previews do not change location when the variable changes, is there a way to re-point the files to the new location?

Thank you

**Comment by frankrousseau** [comment]
Hello @Animatect, 
Make sure that the `zou` user has all the required permission and that the zou environment variables are properly set (https://zou.cg-wire.com/configuration/). The variable that is concerned is `PREVIEW_FOLDER`.

**Comment by Animatect** [comment]
Hi Frank, thank you for the reply the problem is with the pemision, but it's not a problem from zou, I'm going to close the issue
