### ISSUE TITLE
LDAP sync with AD import computer accounts

### ISSUE THREAD

**Issue by mdk-man** [cgwire/zou#575]
Zou v"0.15.19"
Not sure whether it's on purpose or not (I do not see any use case, but maybe there are) but I noticed that syncing Kitsu with AD also import computers present in Active Directory. In AD, computers are part of _user_, _person_ and _computer_ classes (among others).

So, in commands.py around Iine 201, I changed the query so that it only returns object of type "person" OR "user" but not "computer":

query = "(&(|(objectClass=person)(objectClass=user))(!(objectClass=computer)))"

Note, that this query should work too since users are also part of _user_ and _person_ classes in AD:
query = "(&(objectClass=person)(!(objectClass=computer)))"

**Comment by frankrousseau** [comment]
Thank you for this. Can you make a pull request to fix it?

**Comment by mdk-man** [comment]
You are welcome :) I think this bug has been introduced with the solution you provided for Issue #540 (account without firstname/lastname like computers were not imported)

**Comment by frankrousseau** [comment]
Ok great, we'll close this issue when your fix will be released!

**Comment by Plyrolith** [comment]
The new fix breaks sync in non-AD LDAP, where “computers” may not exist.

**Comment by frankrousseau** [comment]
@Plyrolith I'm sorry but your request is very fuzzy. Can you be more specific?

**Comment by mdk-man** [comment]
I just made a pull request to fix this. I didn't know that computer class was not a default ldap class !
