### ISSUE TITLE
Feature to check if DB and data have bin initiated

### ISSUE THREAD

**Issue by EmberLightVFX** [cgwire/zou#597]
It would be great to have a feature to check if the connected DB have bin initiated with tables and data to work with Kitsu or if the database is clean and needs its init-db and init-data.

If there also would be an option to check if an admin account has bin created already, that would help a lot also to see where in the installation state we're currently at.

**Comment by frankrousseau** [comment]
The feature has been added: a `is-db-ready` command is available.
