### ISSUE TITLE
having error when setup ZOU Create-Admin!!

### ISSUE THREAD

**Issue by danu2811** [cgwire/zou#606]
hi, I have an issue when create admin user!! im using ubuntu to do the zou setup.
here is the error

DB_PASSWORD=manimonki zou create-admin danu@manimonki.com
Usage: zou create-admin [OPTIONS] EMAIL
Try 'zou create-admin --help' for help.

Error: Missing option '--password'.

hope you can help
Desmond

**Comment by EvanBldy** [comment]
Hi @danu2811, you need to set the password of the admin with the switch --password yourpassword.
