### ISSUE TITLE
Unable to Login Using URL-Encoded Data in Request Body

### ISSUE THREAD

**Issue by NickTiny** [cgwire/zou#621]
# Bug Description
***Reported on behalf of the [Blender Studio](https://studio.blender.org/).***

Authenticating with the API via cURL was possible as described in this documenation: https://zou.cg-wire.com/api/#api 

`curl -X POST <server_address>/auth/login -d "email=<email>&password=<password>` 

It is no longer possible to log in using URL-encoded data in the request body.

# Expected Result
Expected response status code: `200` 

# Actual Result
`unable to authorize (status code=400)`

# Workaround
To work around this issue, we have to use JSON payload in the request body. 
`curl -X "POST" "<server_address>/auth/login?email=<email>&password=<password>" \ -H 'Content-Type: application/json; charset=utf-8' \ -d $'{ }'`

**Comment by EvanBldy** [comment]
Hi @NickTiny, 
Thanks for reporting this.
It's due to the recent upgrade of Flask and Flask_RESTful / reqparse, I will try to find a quick solution for that today.
But the big solution will be to stop using Flask_Restful / reqparse and use webargs : what i'm working on right now.

**Comment by EvanBldy** [comment]
Hi again @NickTiny,
I have found a quick solution for your problem it's in this PR : https://github.com/cgwire/zou/pull/622.
I have also made a new version (0.16.9), can you try this version and close the issue if it's okay for you ? 
Have a nice day

**Comment by NickTiny** [comment]
@EvanBldy This fix does resolve the issue, it now works as it use to. 

Appreciate the prompt response!

closing ticket!
