### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by frankrousseau** [cgwire/zou#64]
Log generates big files, it would be better to logrotate them.

https://stackoverflow.com/questions/36424335/log-rotation-with-gunicorn

**Comment by frankrousseau** [comment]
Note for further adding to documentation:

Add this folder:
```
mkdir /var/run/zou
chown zou: /var/run/zou
```

Add this line to gunicorn configuration file:
```
PIDFile=/var/run/zou/zou.pid
```

Add this logrotate configuration (`/etc/logrotate.d/zou`)

```
/var/log/gunicorn/gunicorn_access.log {
    daily
    missingok
    rotate 14
    compress
    notifempty
    create 640 user group
    postrotate
        kill -USR1 `cat /run/zou/zou.pid`
    endscript
}
```

**Comment by frankrousseau** [comment]
I added a section about this in the official documentation:
https://zou.cg-wire.com/log_rotation/

**Comment by LarsCawley** [comment]
I am trying to follow the log rotation instruction, but I find that the pid files are not being created.  I am not sure if I am missing something.  I have added the following lines to the gunicorn-events.conf which gets me the dir when my system starts.
RuntimeDirectory=zou
ExecStartPre=+/usr/bin/chown zou: /var/run/zou

**Comment by LarsCawley** [comment]
Ubuntu 20.04.01
Zou 0.12.5
Kitsu 0.12.2
I am trying to follow the log rotation instruction, but I find that the pid files are not being created. I am not sure if I am missing something. I have added the following lines to the gunicorn-events.conf which creates the dir when my system starts.
RuntimeDirectory=zou
ExecStartPre=+/usr/bin/chown zou: /var/run/zou

**Comment by frankrousseau** [comment]
This problem is not related to zou. It's more related to a configuration in the system. I reopened the issue in case someone has an answer.

**Comment by frankrousseau** [comment]
This stackoverflow question may help you:

```
https://stackoverflow.com/questions/26902930/how-do-i-restart-gunicorn-hup-i-dont-know-masterpid-or-location-of-pid-file#42361529
```

**Comment by LarsCawley** [comment]
I have mine working now.  If it can help others I have made some edits [in this docs update](https://github.com/cgwire/zou/pull/285)

**Comment by frankrousseau** [comment]
Ok, let's say it's a solved problem. Thank you @LarsCawley!
