### ISSUE TITLE
Deleting a preview doesn't delete all related files on server

### ISSUE THREAD

**Issue by dragonbleapiece** [cgwire/zou#648]
**Context**

Studio name: Malil'Art
Zou version: 0.16.19
Zou installation type: self-hosted

**Describe the bug**
Deleting a preview task doesn't delete lowdef movie and pictures thumbnails and original.

In other words, related files in :
`/opt/zou/previews/movies/lowdef`
`/opt/zou/previews/pictures/thumbnails`
`/opt/zou/previews/pictures/original`

Are not deleted.

**Expected behavior**
I expect that deleting a preview delete all used files for the preview.

**Comment by frankrousseau** [comment]
Thank you @dragonbleapiece for the report!

**Comment by frankrousseau** [comment]
ping @EvanBldy

**Comment by EvanBldy** [comment]
Hi @dragonbleapiece, 
Thanks for the report !
In the next release, you need to set the environment variable "REMOVE_FILES" to True in your Zou service.
Thanks :)
