### ISSUE TITLE
`dump-database` command creates two backup files

### ISSUE THREAD

**Issue by dragonbleapiece** [cgwire/zou#654]
**Context**

Studio name: Malil'Art
Zou version: 0.16.19
Zou installation type: self-hosted

**Describe the bug**
The command creates one file in the current directory of the `dump-database` command execution and copy it in the `dbbackup` folder. So two files are generated whereas it doesn't seem to be useful.

**Expected behavior**
The command should give only one backup file (in the `dbbackup`, I suppose).

**Comment by EvanBldy** [comment]
Hi @dragonbleapiece,
Thanks for the report. 
I have added a flag to the command dump-database (--store), if the flag is not set it will only create the dump in the current directory. If the flag is set, it will only create the dump in <preview_folder>/files/dbbackup.
It's in this PR : https://github.com/cgwire/zou/pull/683
