### ISSUE TITLE
Thumbnail View of Revisions akin to Multiple File Uploads

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/zou#678]
Same as what we have for the multiple file upload thumbnails, but at the top of the review panel showcasing the revisions and respective numbering for at-a-glance.

These should be on by default if the task panel is pulled out to a larger size.

**Comment by EvanBldy** [comment]
Hi @PeteDraper, 
Thanks for the report, this is related to Kitsu.
Can you add this issue on the repo for kitsu ? 
Have a nice day
