### ISSUE TITLE
Update crash

### ISSUE THREAD

**Issue by johnnycoolideer** [cgwire/zou#682]
I’ve been upgrading my raspberry pi but suddenly Kitsu stopped working.  It allowed you to login but then had an infinite spinning loading screen.  I’ve tried to update Zou but the machine completely freezes here:-

![IMG_8032](https://github.com/cgwire/zou/assets/99082293/3674e5ec-5991-446a-be48-34fb6c588ee1)

And now I have this:-

![IMG_8033](https://github.com/cgwire/zou/assets/99082293/03a9e490-ce5b-4d07-bb5a-1def5931e58c)

Any ideas?

**Comment by johnnycoolideer** [comment]
There isn’t any error message sadly the wheel thing stops spinning at the computer locks.

**Comment by johnnycoolideer** [comment]
Video of the issue.

[Zou Update Error](https://youtu.be/TGX5tr4lBWk)

**Comment by EvanBldy** [comment]
I think you need to try that to see the errors : 
https://opentimelineio.readthedocs.io/en/latest/tutorials/quickstart.html#developer-quickstart
It will try only to build OTIO.

**Comment by johnnycoolideer** [comment]
Here’s the errors from following the opening 3 lines in a virtual python environment.

![IMG_8037](https://github.com/cgwire/zou/assets/99082293/9c5500ac-28c8-48e7-a60e-79c2cff209c9)

And

![IMG_8039](https://github.com/cgwire/zou/assets/99082293/964f1641-7a49-4387-8cfe-4ba23181a5ec)

**Comment by johnnycoolideer** [comment]
I’ve managed to fix the bottom one by installing cmake and it’s prerequisites but running it then locks the pie in the wheel building line as before.

**Comment by johnnycoolideer** [comment]
Ok I worked out the prerequisite pyside6 doesn’t install with python 3.10 and above so I got it working with 3.8 and now have this error message:-

![Uploading IMG_8040.jpeg…]()

**Comment by johnnycoolideer** [comment]
Ok I worked out the prerequisite for this called pyside6 isn’t compatible with python 3.10 and above so changed to 3.8.  It now tries to run but I get this:-

![IMG_8040](https://github.com/cgwire/zou/assets/99082293/66db95d5-91b4-48d6-9896-9eaa9c3837ed)

**Comment by johnnycoolideer** [comment]
Fixed that and it went back to the original error message.  I’m perplexed.

**Comment by frankrousseau** [comment]
It seems that the Rasberry Pi is not able to download the OpenTimelineIO dependency

**Comment by johnnycoolideer** [comment]
Bizarre isn’t it? I’ve managed to get it back to the point where I have Kitsu’s login screen, however when I put in the user name and password I just get a spinning loading screen that never ends.

![IMG_8046](https://github.com/cgwire/zou/assets/99082293/83e1a07f-f3f9-48ad-ae26-287ef13f68bb)

**Comment by frankrousseau** [comment]
It means that the API is crashed.

**Comment by frankrousseau** [comment]
You have to fix the OpentimelineIO issue first, then finalize the update and restart the server.

**Comment by johnnycoolideer** [comment]
Interestingly just tried to do a brand new install from scratch and when it hit the Zou install section and started doing opentimelineio it actually closed the terminal window.

**Comment by johnnycoolideer** [comment]
Ok so I bought a new raspberry pie as I suspected it was a memory issue.  Good news is it worked!  I’m passed the opentimelineio issue.  The bad news, it’s still not working.  

When I initialise the database I get this:-

![IMG_8056](https://github.com/cgwire/zou/assets/99082293/7a584b10-1431-4f3e-91dc-84267ed4ab68)

and I now can’t login:-

![IMG_8057](https://github.com/cgwire/zou/assets/99082293/36292628-aa35-4cb0-8b78-703a1de8def5)

if I try and create a new admin I get this:-

![IMG_8059](https://github.com/cgwire/zou/assets/99082293/0af957d2-6058-467d-800c-739fa6166ebb)

**Comment by EvanBldy** [comment]
Hi @johnnycoolideer, you need to do a `zou upgrade-db` I think

**Comment by johnnycoolideer** [comment]
Yeah tried that with no joy.  Went for a from scratch rebuild which has worked but it’s a shame that we lost data.  One last thing will sudo update and upgrade commands also update Kitsu and Zou or does that have to be done manually?

**Comment by EvanBldy** [comment]
@johnnycoolideer for now Zou and Kitsu are not in a debian package. So it can't be managed by package manager like APT and you have to do the upgrades manually. You have all the documentation to do that here : https://zou.cg-wire.com/#update.
If you don't want to manage that, we (CGWire) provide services for that, cloud or on premise.
Can I close your issue if you don't have any other question ? 
Cordially

**Comment by johnnycoolideer** [comment]
Yes mate you can, thank you.
