### ISSUE TITLE
Error after enabling postgres remote access

### ISSUE THREAD

**Issue by aramadan0096** [cgwire/zou#688]
**Context**

Studio name: Personal usage
Kitsu version: 0.15.11
Production type: VFX

**Describe the bug**

System crash after trying enabling remote access to postgresql.

**Screenshots**

![image](https://github.com/cgwire/kitsu/assets/57462754/a30b1197-c6e6-4cb3-b771-1a8ade9f74f1)

**Desktop (please complete the following information):**

 - OS: Ubintu
 - Browser chrome

**Comment by EvanBldy** [comment]
Hi @aramadan0096, 
Can you provide more informations, we can't help you here.
How Zou is installed ? (docker / local installation)
What do you mean by "enabling remote access to postgresql" ? 
Is possible to have zou logs ? (in opt/zou)

If it's difficult for you to manage Kitsu/Zou we can manage the instance for you. See on our website : https://www.cg-wire.com/kitsu

Cordially,

**Comment by aramadan0096** [comment]
> Hi @aramadan0096, 
> Can you provide more informations, we can't help you here.
> How Zou is installed ? (docker / local installation)
> What do you mean by "enabling remote access to postgresql" ? 
> Is possible to have zou logs ? (in opt/zou)
> 
> If it's difficult for you to manage Kitsu/Zou we can manage the instance for you. See on our website : https://www.cg-wire.com/kitsu
> 
> Cordially,
> 

I followed this tutorial:
Setting up a remote Postgres database server on Ubuntu 18.04 - LogR...

To be able to connect to the Zou database using pgAdmin from another computer on the same network

**Comment by EvanBldy** [comment]
You need to check the status of postgresql.service
