### ISSUE TITLE
Use an invalid metadata type raised a global internal error

### ISSUE THREAD

**Issue by NicoPennec** [cgwire/zou#693]
**Context**

Studio name: all
Zou version: 0.17.23
Zou installation type: all

**Describe the bug**
You can push an invalid metadata descriptor type from an API call to Zou.
The API will accept the `"test"` value as `data_type` as below, and return an HTTP 200 response.

> PUT /data/projects/{id}/metadata-descriptors/{id}  => 200
>
>Body:
>{
  "id": "***",
  "name": "data",
  "data_type": "test",
  "choices": ["a", "b", "c"],
  "for_client": false,
  "entity_type": "Asset",
  "departments": []
}

But then, the load context endpoint will crash with an internal server error:

> GET /data/user/context => 500 (INTERNAL SERVER ERROR)
>
> Stacktrace:
>  [...]
>  File \"/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy_utils/types/choice.py\", line 194, in process_result_value
>    return Choice(value, self.choices_dict[value])
>  KeyError: 'test'

**Expected behavior**
Reject the invalid value of `data_type` on PUT call (see [valid values](https://github.com/cgwire/zou/blob/master/zou/app/models/metadata_descriptor.py#L20-L26))

**Additional context**
As a quick test, you can delete one valid value from the `METADATA_DESCRIPTOR_TYPES` array, if it's already used by the current project, and reload your kitsu instance.

**Comment by frankrousseau** [comment]
It was fixed. Thank you!
