### ISSUE TITLE
Kitsu encountered an error while reaching its data API.

### ISSUE THREAD

**Issue by MitchWoodin** [cgwire/zou#767]
**Context**

Studio name: 
Zou version: 
Zou installation type: (for example: hosted by CGWire, self-hosted, docker etc)

**Describe the bug**
Trying to access localhost kitsu server. It's throwing the error seen in the screenshot below. I've checked the status of the zou server and it's running and enabled. I tried restarting the server but that has had no effect. 

**Expected behavior**
I should be seeing my kitsu site.

**Screenshots**
![image](https://github.com/cgwire/zou/assets/42667068/17ad8d72-5ef1-4ab6-b47c-c8f021ec6ce7)

**Additional context**
Response from localhost:5000/status:
{"name": "Zou", "version": "0.15.37", "database-up": true, "key-value-store-up": true, "event-stream-up": true, "job-queue-up": false}

Response from `sudo systemctl status zou`:
```
● zou.service - Gunicorn instance to serve the Zou API
     Loaded: loaded (/etc/systemd/system/zou.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-02-02 19:35:01 AEDT; 7s ago
   Main PID: 74899 (gunicorn)
      Tasks: 7 (limit: 154169)
     Memory: 352.5M
        CPU: 3.575s
     CGroup: /system.slice/zou.service
             ├─74899 /opt/zou/zouenv/bin/python /opt/zou/zouenv/bin/gunicorn -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app
             ├─74902 /opt/zou/zouenv/bin/python /opt/zou/zouenv/bin/gunicorn -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app
             ├─74903 /opt/zou/zouenv/bin/python /opt/zou/zouenv/bin/gunicorn -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app
             └─74904 /opt/zou/zouenv/bin/python /opt/zou/zouenv/bin/gunicorn -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app

Feb 02 19:35:01 mitchell-mint systemd[1]: Started Gunicorn instance to serve the Zou API.
Feb 02 19:35:01 mitchell-mint gunicorn[74899]: !!!
Feb 02 19:35:01 mitchell-mint gunicorn[74899]: !!! WARNING: configuration file should have a valid Python extension.
Feb 02 19:35:01 mitchell-mint gunicorn[74899]: !!!
```

**Comment by EvanBldy** [comment]
Hi @MitchWoodin, 
Can you open your console logs in the browser and copy them here ? 
Thanks

**Comment by MitchWoodin** [comment]
XHRGET
http://localhost/socket.io/?EIO=4&transport=polling&t=Orf43TW
[HTTP/1.1 502 Bad Gateway 955ms]

XHRGET
http://localhost/api/auth/authenticated
[HTTP/1.1 502 Bad Gateway 944ms]

XHRGET
http://localhost/api/config
[HTTP/1.1 502 Bad Gateway 934ms]

XHRGET
http://localhost/api/config
[HTTP/1.1 502 Bad Gateway 933ms]

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools vue.js:9323:57
Error: Bad Gateway
    Ae client.js:420
    emit index.js:145
    _end client.js:710
    _end client.js:689
    end client.js:666
    init crisp.js:5
    mounted App.vue:75
    VueJS 14
    <anonymous> main.js:54
crisp.js:7:16
Uncaught (in promise) Error: Bad Gateway
    Ae client.js:420
    emit index.js:145
    _end client.js:710
    _end client.js:689
    end client.js:666
    _fullfilledPromise request-base.js:266
    then request-base.js:250
    pget client.js:40
    getConfig client.js:123
    setMainConfig main.js:73
    registerAction vuex.esm.js:851
    dispatch vuex.esm.js:516
    dispatch vuex.esm.js:406
    d vuex.esm.js:1064
    mounted App.vue:76
    VueJS 14
    <anonymous> main.js:54
client.js:420:20
XHRGET
http://localhost/api/auth/authenticated
[HTTP/1.1 502 Bad Gateway 0ms]

XHRGET
http://localhost/socket.io/?EIO=4&transport=polling&t=Orf4469
[HTTP/1.1 502 Bad Gateway 0ms]

XHRGET
http://localhost/socket.io/?EIO=4&transport=polling&t=Orf44OL
[HTTP/1.1 502 Bad Gateway 0ms]

XHRGET
http://localhost/socket.io/?EIO=4&transport=polling&t=Orf4595
[HTTP/1.1 502 Bad Gateway 0ms]

XHRGET
http://localhost/socket.io/?EIO=4&transport=polling&t=Orf46Os
[HTTP/1.1 502 Bad Gateway 0ms]

XHRGET
http://localhost/socket.io/?EIO=4&transport=polling&t=Orf47d5
[HTTP/1.1 502 Bad Gateway 0ms]

**Comment by frankrousseau** [comment]
You should check your Nginx configuration. It seems it doesn't redirect properly to the server API.

**Comment by EvanBldy** [comment]
Hi @MitchWoodin,
Sorry, I will close this issue as @frankrousseau said it's probably an error on your nginx configuration (there's no Zou error).
If you have difficulty managing a self-hosted instance of Kitsu we provide cloud instance, see here : https://www.cg-wire.com/pricing
