### ISSUE TITLE
Changing a shot name

### ISSUE THREAD

**Issue by PabloRedondoCone** [cgwire/zou#805]
**Context**

Studio name: Naolito
Zou version: 0.19.27
Zou installation type: Docker

**Describe the bug**
I want to change the name of a shot, and after using data/shots/shot_id I receive a "HTTP/1.1 405 Method Not Allowed", but if I use /data/entities/entity_id, I can pertfectly change the shot's name

**Expected behavior**
I expected a successful name change using data/shots/shot_id.

**Comment by frankrousseau** [comment]
The route is now available.
