### ISSUE TITLE
Include sequence/episode tasks in the project schedule overview

### ISSUE THREAD

**Issue by JW-vfx** [cgwire/zou#837]
Would it be possible to add sequence/episode tasks in the project schedule? Some tasks needs to still be visible in the project overview schedules, but not necessary clutter the shots/assets tasks. For instance, conform, grade, delivery etc. These tasks still need artist and schedule allocations, but don't need them on a shot per shot or asset basis. 
Keep up the good work! Thankyou

**Comment by frankrousseau** [comment]
Thank you @JW-vfx for reporting. I moved it to Canny our feature request platform for Kitsu. These issues are dedicated to bugs related to the Kitsu API (Zou).
