### ISSUE TITLE
Cannot fetch metadata-descriptors as an artist or a supervisor

### ISSUE THREAD

**Issue by ChristopheSeux** [cgwire/zou#848]
There is a permission restriction in the api that prevent an artist or a supervisor to fetch the metadatadescriptor of a project.
In the kitsu interface an artist can see all the metadatas but cannot edit them (Which is good)
But with the api it's impossible to get the complete list of metadadescriptor which make it hard as a TD to make custom interfaces.
An artist or a supervisor should be able to fetch the complete list of metadadescriptor as there is no sensible information there, but for sure have restricted permissions to edit them

**Comment by frankrousseau** [comment]
Can you tell us which gazu function you are using or which zou route?

**Comment by ChristopheSeux** [comment]
The gazu function used are gazu.project.all_metadata_descriptors() and get_metadata_descriptor_by_field_name()
The zou routes are "data/projects/%s/metadata-descriptors" % project["id"] and data/metadata-descriptors'
I get gazu.exception.NotAllowedException for both.
I checked and the artist and the supervisor are in the team of the project

**Comment by frankrousseau** [comment]
It should be fixed. Can you test it?
