### ISSUE TITLE
Production thumbnail has incorrect size

### ISSUE THREAD

**Issue by johhnry** [cgwire/zou#850]
**Context**

Studio name: Welcome To Love
Kitsu version: 0.19.53
Production type: 

**Describe the bug**

When uploading a square thumbnail for a production (200x200 pixels), the resulting thumbnail is croped and stretched incorrectly (it should keep its original size to fill the widget).

**Screenshots**

![image](https://github.com/user-attachments/assets/40e27c31-92f6-419c-b7eb-f1a63e3407c8)
![image](https://github.com/user-attachments/assets/f6138113-143d-4253-81f3-8853144f1231)

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Firefox
 - Version: 129.0.2

**Comment by NicoPennec** [comment]
Thanks for the report @johhnry 🙏 

The following API endpoint generates a thumbnail with a wrong ratio of 150x100px (width/height) instead of 100x100px thumbnail:
```
POST /api/pictures/thumbnails/projects/<project-id>
 ```

**Comment by EvanBldy** [comment]
Hi @johhnry,
It will be fixed with this PR : https://github.com/cgwire/zou/pull/851

**Comment by johhnry** [comment]
Thanks a lot @EvanBldy !
