### ISSUE TITLE
Following documentation on Updating kitsu will delete preview folder

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/zou#898]
**Context**

We got asked on discord about this issue by a user

**Describe the bug**

The documentation at [https://zou.cg-wire.com/#update-kitsu](https://zou.cg-wire.com/#update-kitsu) suggests deleting the kitsu folder and remaking it before getting and extracting the latest release

```bash
sudo rm -rf /opt/kitsu/dist
sudo mkdir /opt/kitsu/dist
```

This folder contains the /preview folder which contains all videos and reviews - deleting it will delete all previews for that user.

I'd suggest switching back to the old way of getting the latest on github or making sure users back up their previews ( many are not toooooo versed in Linux admin and will execute `sudo rm -rf` without batting an eye. ( I'd suggest this as critical as users seem to delete their previews currently )

**Comment by frankrousseau** [comment]
@tetsuoanimation I transfered the issue in the zou repositiory where it below.

**Comment by tetsuoanimation** [comment]
Hmmmm then the docs are right and they installed it wrong - I verified on my install: /previews is in /zou

**Comment by tetsuoanimation** [comment]
Yeah following the docs tells you to install zou first and create the previews folder
```bash
sudo mkdir /opt/zou/previews
sudo chown -R zou:www-data /opt/zou/previews
```

Then you download and copy kitsu to its own folder. 
```bash
sudo mkdir -p /opt/kitsu/dist
curl -L -o /tmp/kitsu.tgz $(curl -v https://api.github.com/repos/cgwire/kitsu/releases/latest | grep 'browser_download_url.*kitsu-.*.tgz' | cut -d : -f 2,3 | tr -d \")
sudo tar xvzf /tmp/kitsu.tgz -C /opt/kitsu/dist/
rm /tmp/kitsu.tgz
```

Docs seem clear if they followed them correctly - can be closed as 'user error'?
