### ISSUE TITLE
Long and short names.

### ISSUE THREAD

**Issue by tokejepsen** [cgwire/zou#90]
**Issue**

Defining long names for properties might cause issue when mapping to other systems.

**Description**

This issue originated from [Avalon](https://github.com/getavalon/docker/issues/26) where a project with whitespaces does not comply with Avalon's database.

Commonly among production trackers are a way to define a long and short name for a property. The long name is a visual aid for the end user, and the short name is for code.

Long and short name might not be the best definition. Other options include:

- Label/name
- Name/code

**Comment by frankrousseau** [comment]
I'm not sur to understand what you mean. About what kind of data are you talking about?

**Comment by tokejepsen** [comment]
For example the project name can have white spaces, same goes for assets. Avalon does not allow to have whitespaces in the project/asset name.

When we sync data from CGWire to Avalon, we could sanitize the data (remove whitespace etc.), but that will cause an issue when syncing data from Avalon to CGWire.
In Ftrack for example the user sees and inputs a name for the project, lets say "Dark Knight" but they also register "dark_knight" as ```project["code"]```.

I've also seen production tracker where you can register regex expression to validate what the user inputs.

**Comment by frankrousseau** [comment]
Ok got it. One more thing to investigate. Thank you!

**Comment by frankrousseau** [comment]
I'm going to add a `short_name` field to entities. I agree that the naming `name` / `short_name` is not as good as Label/Name or Code/Label but changing this would break too much thing.

**Comment by frankrousseau** [comment]
Sorry, but I changed my mind. For entities, it's not about setting a short name. It's about allowing a santized name. So I'm going to add a `code` field to projects and entities.

**Comment by tokejepsen** [comment]
Awesome! What are the specs for the code field? Will there be a regex to comply with?

**Comment by frankrousseau** [comment]
I wast just thinking about adding a free field. But if you propose a constraint we can add it.

**Comment by tokejepsen** [comment]
How is the field for out? Is it the user/developer doing this?

I would propose lower snakecase, and not allow special characters, so the code could eventually be used on disk for example without issues.

**Comment by frankrousseau** [comment]
Ok thank you

**Comment by frankrousseau** [comment]
I added the code fields but I didn't put any constraint on them.

**Comment by frankrousseau** [comment]
Is the problem solved for you @tokejepsen?

**Comment by tokejepsen** [comment]
Yes, @frankrousseau the `code` field will work. Thanks!
