### ISSUE TITLE
Error while uploading a video file when publishing a new version in Kitsu

### ISSUE THREAD

**Issue by PrettyPurpleInk** [cgwire/zou#901]
**Context**

Studio name: Animationsinstitut, Filmakademie Ludwigsburg
Zou version: 0.19.72
Zou installation type: self-hosted docker (emberlightvfx/zou-for-docker)

**Describe the bug**
When uploading a MP4 video file through the webinterface it aborts with `An error occurred while posting comment`. Logs show the following error:

```
cgwire-zou-app      | [2024-12-18 16:14:06,226] ERROR in resources: 'int' object has no attribute 'replace'
cgwire-zou-app      | Traceback (most recent call last):
cgwire-zou-app      |   File "/usr/local/lib/python3.11/site-packages/zou/app/blueprints/previews/resources.py", line 278, in post
cgwire-zou-app      |     self.save_movie_preview(instance_id, uploaded_file, normalize)
cgwire-zou-app      |   File "/usr/local/lib/python3.11/site-packages/zou/app/blueprints/previews/resources.py", line 352, in save_movie_preview
cgwire-zou-app      |     preview_files_service.prepare_and_store_movie(
cgwire-zou-app      |   File "/usr/local/lib/python3.11/site-packages/zou/app/services/preview_files_service.py", line 202, in prepare_and_store_movie
cgwire-zou-app      |     fps = get_preview_file_fps(project, entity)
cgwire-zou-app      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cgwire-zou-app      |   File "/usr/local/lib/python3.11/site-packages/zou/app/services/preview_files_service.py", line 104, in get_preview_file_fps
cgwire-zou-app      |     fps = entity_data["fps"].replace(",", ".")
cgwire-zou-app      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
cgwire-zou-app      | AttributeError: 'int' object has no attribute 'replace'
```

**This only happens when a value is entered in the FPS field of the shot / asset.**

**Expected behavior**
Video file uploads and gets processed without error.

**Additional context**
The code probably expects a string type for the fps value but it is a number. I wonder if a reformat is necessary here at all.
Line in question: https://github.com/cgwire/zou/blob/e4ee5fcaa666518d69d7f91bd5eaa17c790e7a92/zou/app/services/preview_files_service.py#L104

**Comment by EvanBldy** [comment]
Hi @PrettyPurpleInk,
Thanks for the report, it will be fixed in the next Zou release.
